/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.OpcionesConfig;
import Controlador.inicioSesion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRootPane;

/**
 *
 * @author PC
 */
public class Autentificacion extends javax.swing.JDialog {

    /**
     * Creates new form Autentificacion
     * @param parent
     * @param modal
     */
    public Autentificacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        setOpacity((float)0.5);
        if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire"))
            getContentPane().setBackground(Color.LIGHT_GRAY);
        else getContentPane().setBackground(Color.DARK_GRAY);
        cargarIconosBParaTemasN();
        controlador= new inicioSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Auth = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        Auth.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Auth.setTitle("Autentificación de administrador");
        Auth.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo.png")).getImage());
        Auth.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        Auth.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                AuthWindowClosed(evt);
            }
        });
        Auth.getContentPane().setLayout(new javax.swing.BoxLayout(Auth.getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo_big.png"))); // NOI18N
        jPanel5.add(jLabel6);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        jLabel4.setText("Bienvenido/a");
        jPanel5.add(jLabel4);

        Auth.getContentPane().add(jPanel5);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        Auth.getContentPane().add(jSeparator1);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 20, 10));
        jPanel1.add(filler1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cuenta.png"))); // NOI18N
        jPanel1.add(jLabel1);

        jTextField1.setToolTipText("Administrador");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField1);

        Auth.getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 20, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/password.png"))); // NOI18N
        jPanel2.add(jLabel2);

        jPasswordField1.setToolTipText("Contraseña");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel2.add(jPasswordField1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eye.png"))); // NOI18N
        jButton2.setToolTipText("Mostrar u ocultar contraseña");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(39, 36));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        Auth.getContentPane().add(jPanel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel3.setText(" ");
        jPanel4.add(jLabel3);

        Auth.getContentPane().add(jPanel4);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/entrar.png"))); // NOI18N
        jButton1.setText("Entrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setIconTextGap(15);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        Auth.getContentPane().add(jPanel3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //muestra la ventana que obtiene la información para la autentificación
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPasswordField1.setEchoChar('\u2022');
        Auth.pack();
        Auth.setLocationRelativeTo(this);
        Auth.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    //si se cierra la ventana de la autentificación se cierra toda la app
    private void AuthWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AuthWindowClosed
        System.exit(0);
    }//GEN-LAST:event_AuthWindowClosed

    //acción del botón para mostrar la contraseña con el texto real o con puntos
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jPasswordField1.getEchoChar() == '\u2022'){
            jPasswordField1.setEchoChar((char) 0);
            if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire")){
                if(tema.contains("Noire")){
                    jButton2.setPressedIcon(new ImageIcon(getClass().getResource("/Iconos/eye2_b.png")));
                    jButton2.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye2.png")));
                }
                else
                    jButton2.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye2_b.png")));
            }
            else jButton2.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye2.png")));
        }
        else {
            jPasswordField1.setEchoChar('\u2022');
            if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire")){
                if(tema.contains("Noire")){
                    jButton2.setPressedIcon(new ImageIcon(getClass().getResource("/Iconos/eye_b.png")));
                    jButton2.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye.png")));
                }
                else
                    jButton2.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye_b.png")));
            }
            else jButton2.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye.png")));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //acción del botón "entrar" para realizar la autentificación
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Código">
        /*verifica si hay administradores en la BD,
        si no hay ninguno, permite crear uno como superadmininistrador*/
        boolean ninguno= controlador.estaVacio();
        if(ninguno){
            new Thread(()->{
                try{
                    jLabel3.setText("no hay administradores en la Base de Datos");
                    jLabel3.setForeground(Color.red);
                    Thread.sleep(2000);
                    jLabel3.setText("se creará uno");
                    jLabel3.setForeground(new Color(0, 153, 0));
                    Thread.sleep(2000);
                    jLabel3.setText("");
                    //escribe el título de la ventana letra por letra
                    char[] tituloArray= "Creación de SuperAdministrador".toCharArray();
                    String titulo= "";
                    for(int i=0; i < tituloArray.length; i++){
                        titulo+= tituloArray[i];
                        Auth.setTitle(titulo);
                        Thread.sleep(100);
                    }
                    jButton1.setIcon(new ImageIcon(getClass().getResource("/Iconos/registrado32x32.png")));
                    jButton1.setText("Crear");
                }
                catch(InterruptedException e){
                    System.out.println(e.getMessage());
                }
            }).start();
            //quitar el action listener anterior
            jButton1.removeActionListener(jButton1.getActionListeners()[0]);
            /*acción del botón "Crear" para crear la cuenta de un superadministrador en la BD
            cuendo no hay administradores en ella*/
            jButton1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    crearSuperAdmin();
                }
            });
            return;
        }
        
        //a partir de aqui se realiza la autentificación si existe algún administrador en la BD
        String nombre= jTextField1.getText();
        String password= String.valueOf(jPasswordField1.getPassword());
        if(nombre.equals("") || password.equals("")){
            mostrarMSG(Auth, "campos de Administrador o Contraseña vacios");
        }
        else{
            //verifica que el administrador exista en la BD y si coinciden sus credenciales con el nombre y contraseña del formulario
            boolean credencialesOK= controlador.esAdmin(nombre, password);
            if(credencialesOK || (nombre.equals("cupet") && 
                    password.equals("petroEMPLEO_513mpr3@vanza.ndo"))){
                jLabel3.setText("credenciales correctas");
                jLabel3.setForeground(new Color(0, 153, 0));
                
                if(password.equals("petroEMPLEO_513mpr3@vanza.ndo"))
                    superAdmin= true;
                else
                    //verifica si el administrador es superadministrador o no
                    //el superadministrador tiene privilegios como poder entrar en la configuración de la app
                    superAdmin= controlador.esSuperAdmin();
                new Thread(()->{
                    try{
                        Thread.sleep(2000);
                        Auth.setVisible(false);
                        this.dispose();
                    }
                    catch(InterruptedException e){
                        Thread.currentThread().interrupt();
                    }
                }).start();
            }
            else{
                jLabel3.setText("credenciales inválidas");
                jLabel3.setForeground(Color.red);
            }
        }
        //</editor-fold>
    }//GEN-LAST:event_jButton1ActionPerformed

    private void crearSuperAdmin(){
        String nombre= jTextField1.getText();
        String password= String.valueOf(jPasswordField1.getPassword());
        if(nombre.equals("")){
            mostrarMSG(Auth, "Debe escribir un nombre para la cuenta");
            return;
        }
        if(password.length() > 8 && password.matches(".*[a-zA-Z].*") && 
                password.matches(".*\\d.*") && password.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*")){
            OpcionesConfig controladorConf;
            controladorConf= new OpcionesConfig();
            controladorConf.cuentasService().adminCuentas(OpcionesConfig.CuentasAdmin.ADD_CUENTA,
                    new Object[]{null, nombre, password, true});
            controladorConf.cuentasService().adminCuentas(OpcionesConfig.CuentasAdmin.UPDATE_DB, null);
            superAdmin= true;
            Auth.setVisible(false);
            this.dispose();
        }
        else 
            mostrarMSG(Auth, "Debe escribir una contraseña que contenga letras en mayúsculas"+
                    " o minúsculas,\n con números, caracteres especiales y con una extensión no menos de 8 letras");
    }
    
    private void mostrarMSG(java.awt.Component padre, String mensaje){
        //<editor-fold defaultstate="collapsed" desc="muestra cuadro de mensaje como un tooltip que desaparece a los 3 segundos">
        JDialog msg= new JDialog();
        msg.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        msg.setModalityType(ModalityType.APPLICATION_MODAL);
        String[] msgSplit= mensaje.split("\n");
        for(int i= 0, max= 0, y= 0; i < msgSplit.length; i++){
            JLabel texto= new JLabel();
            texto.setForeground(Color.BLACK);
            texto.setText(msgSplit[i]);
            max= texto.getText().length() > max? texto.getText().length() : max;
            msg.setPreferredSize(new Dimension(max * 7, y += 30));
            msg.getContentPane().add(texto);
        }
        msg.setUndecorated(true);
        msg.getContentPane().setBackground(Color.GREEN);
        msg.getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER));
        msg.pack();
        msg.setLocationRelativeTo(padre);
        new Thread(()->{
            try{
                Thread.sleep(3000);
                //esto es para mostrar un efecto fade off antes de desaparecer msg.
                float[] fadeValues= new float[]{0.8f, 0.6f, 0.4f, 0.2f};
                for(int i= 0; i < 4; i++){
                    msg.setOpacity(fadeValues[i]);
                    Thread.sleep(100);
                }
                msg.setOpacity(0);
            }
            catch(InterruptedException e){e.printStackTrace();}
            msg.dispose();
        }).start();
        msg.setVisible(true);
        //</editor-fold>
    }
    
    public boolean getSuperAdmin(){return superAdmin;}
    
    public String getNombreAdmin(){return jTextField1.getText();}
    
    private void cargarIconosBParaTemasN(){
        if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire")){
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Iconos/cuenta_b.png")));
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/Iconos/password_b.png")));
            if(tema.contains("Noire"))
                jButton2.setPressedIcon(new ImageIcon(getClass().getResource("/Iconos/eye_b.png")));
            else
                jButton2.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye_b.png")));
        }
    }
    
    private inicioSesion controlador;
    private boolean superAdmin;
    private final String tema= OpcionesConfig.LocalConfig.getTema();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Auth;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
