/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.OpcionesConfig;
import Controlador.gestionEventos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Configuracion extends javax.swing.JDialog {

    /**
     * Creates new form Configuracion
     * @param parent
     * @param modal
     */
    public Configuracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorConf= new OpcionesConfig();
        cambioTema= false;
        cargarIconosBParaTemasN();
        adminCuentas("asignar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevaCuenta = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(18, 32), new java.awt.Dimension(32767, 32));
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        Vista = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        nuevaCuenta.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        nuevaCuenta.setTitle("Nueva Cuenta");
        nuevaCuenta.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo.png")).getImage());
        nuevaCuenta.setModal(true);
        nuevaCuenta.getContentPane().setLayout(new javax.swing.BoxLayout(nuevaCuenta.getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cuenta.png"))); // NOI18N
        jPanel5.add(jLabel1);

        jTextField1.setToolTipText("Administrador");
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel5.add(jTextField1);

        nuevaCuenta.getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));
        jPanel6.add(filler1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/password.png"))); // NOI18N
        jPanel6.add(jLabel2);

        jPasswordField1.setToolTipText("Contraseña");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel6.add(jPasswordField1);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eye.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel4);

        nuevaCuenta.getContentPane().add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/plus.png"))); // NOI18N
        jButton7.setText("Añadir");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setIconTextGap(10);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);

        nuevaCuenta.getContentPane().add(jPanel7);

        Vista.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Vista.setUndecorated(true);
        Vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VistaMouseClicked(evt);
            }
        });
        Vista.getContentPane().add(jLabel6, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setPreferredSize(new java.awt.Dimension(800, 450));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(570);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Administrador", "Contraseña", "SuperAdmin."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/plus.png"))); // NOI18N
        jButton3.setText("Añadir cuenta");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setIconTextGap(10);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/borrar.png"))); // NOI18N
        jButton4.setText("Eliminar cuenta");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setIconTextGap(10);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/credenciales.png"))); // NOI18N
        jButton5.setText("Cambiar credenciales");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/actualización.png"))); // NOI18N
        jButton6.setText("Actualizar cambios");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setIconTextGap(10);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        jSplitPane1.setRightComponent(jPanel4);

        jPanel1.add(jSplitPane1);

        jTabbedPane1.addTab("Cuentas", null, jPanel1, "Crear o borrar las cuentas de los adminintradores del Sistema");

        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        jLabel3.setText("Temas:");
        jPanel12.add(jLabel3);

        jPanel8.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nimbus (Por defecto)", "Metal", "Motif/CDE", "FlatLaf Darcula", "FlatLaf Dark", "FlatLaf Light", "FlatLaf IntelliJ", "FlatLaf MacDark", "FlatLaf MacLight", "JTattoo Luna", "JTattoo Acryl", "JTattoo Aero", "JTattoo Aluminium", "JTattoo Bernstein", "JTattoo Fast", "JTattoo Graphite", "JTattoo HiFi", "JTattoo McWin", "JTattoo Mint", "JTattoo Noire", "JTattoo Smart", "JTattoo Texture" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel9.add(jScrollPane2);

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setBackground(jTable1.getSelectionBackground());
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(350, 300));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel5);

        jPanel9.add(jPanel11);

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 120, 5));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registrado32x32.png"))); // NOI18N
        jButton8.setText("Aplicar");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setIconTextGap(10);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton8);

        jPanel8.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Apariencia", jPanel8);

        jPanel2.add(jTabbedPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(805, 50));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        jButton1.setText("Guardar");
        jButton1.setToolTipText("Guardar la configuración en un archivo local");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton1);

        jButton2.setText("Resetear");
        jButton2.setToolTipText("Volver a poner toda la configuración a sus valores por defecto");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //acción del botón "Añadir cuenta" para agregar cuentas de administrador
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        seleccionDeBotonesCuentas(jButton3);
        adminCuentas("añadir");
    }//GEN-LAST:event_jButton3ActionPerformed

    //en la ventana "Nueva Cuenta" o "Cambiar Credenciales" muestra u oculta la contraseña cuando se da click en el icono del ojo
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        char echo= jPasswordField1.getEchoChar();
        if(echo == '\u2022'){
            jPasswordField1.setEchoChar((char)0);
            if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire"))
                jLabel4.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye2_b.png")));
            else jLabel4.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye2.png")));
        }
        else {
            jPasswordField1.setEchoChar('\u2022');
            if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire"))
                jLabel4.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye_b.png")));
            else jLabel4.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye.png")));
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /*acción del botón "Añadir" en la ventana "Nueva Cuenta" o
    del botón "Cambiar" en la ventana "Cambiar Credenciales".
    -atención: es la misma ventana y el mismo botón, pero este realiza funciones diferentes
    dependiendo de si es para crear una cuenta nueva o para cambiar las credenciales de una ya creada*/
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Código">
        DefaultTableModel tabla= (DefaultTableModel)jTable1.getModel();
        String AdminName= jTextField1.getText();
        //si el campo del nombre de la cuenta esta vacío muestra un mensaje y sale de la función
        if(AdminName.equals("")){
            mostrarMSG(nuevaCuenta, "Debe escribir un nombre para la cuenta");
            return;
        }
        //verifica que el nombre de la cuenta no sea igual a otro ya existente
        String nombreActual= jButton7.getText().equals("Cambiar")?
                tabla.getValueAt(jTable1.getSelectedRow(), 0).toString() : "";
        if(!AdminName.equals(nombreActual) && controladorConf.checkAdminName(AdminName)){
            mostrarMSG(nuevaCuenta, "Ya existe una cuenta con el mismo nombre");
            return;
        }
        String password= String.valueOf(jPasswordField1.getPassword());
        //si la contraseña tiene más de 8 caracteres y contiene números, letras y caracteres especiales la acepta
        //sino no la acepta y muestra un mensaje y sale de la función
        if(password.length() > 8 && password.matches(".*[a-zA-Z].*") && 
                password.matches(".*\\d.*") && password.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*")){
            //crea la cuenta
            if(jButton7.getText().equals("Añadir")){
                controladorConf.adminCuentas(OpcionesConfig.ADD_CUENTA, new Object[]{null, AdminName, password, false});
                tabla.addRow(new Object[]{AdminName, password, false});
                new Thread(()-> mostrarMSG(this, "Cuenta creada")).start();
            }
            //cambia las credenciales
            else if(jButton7.getText().equals("Cambiar")){
                boolean superAdmin= (boolean)tabla.getValueAt(jTable1.getSelectedRow(), 2);
                controladorConf.adminCuentas(OpcionesConfig.UPDATE_CUENTA, 
                        new Object[]{nombreActual, AdminName, password, superAdmin});
                tabla.setValueAt(AdminName, jTable1.getSelectedRow(), 0);
                tabla.setValueAt(password, jTable1.getSelectedRow(), 1);
                new Thread(()-> mostrarMSG(this, "Credenciales modificadas")).start();
            }
            //oculta la contraseña en la tabla de las cuentas
            String echo= "";
            for(int i= 0; i < password.length(); i++) echo+= '\u2022';
            tabla.setValueAt(echo, jButton7.getText().equals("Añadir")? tabla.getRowCount() - 1 : jTable1.getSelectedRow(), 1);
            nuevaCuenta.setVisible(false);
        }
        else
            mostrarMSG(nuevaCuenta, "Debe escribir una contraseña que contenga letras en mayúsculas o minúsculas,\n"+
                    "con números, caracteres especiales y con una extensión no menos de 8 letras");
        //</editor-fold>
    }//GEN-LAST:event_jButton7ActionPerformed

    //acción del botón "eliminar" para borrar cuentas de administrador
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        seleccionDeBotonesCuentas(jButton4);
        adminCuentas("eliminar");
    }//GEN-LAST:event_jButton4ActionPerformed

    //acción del botón "cambiar credenciales" para cambiar nombre y contraseña de la cuenta escogida
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        seleccionDeBotonesCuentas(jButton5);
        adminCuentas("credenciales");
    }//GEN-LAST:event_jButton5ActionPerformed

    /*acción del botón "Actualizar cambios", el cuál actualiza todas las cuentas existentes de los administradores de la app,
    modificando, eliminando o creando las cuentas en la base de datos según cambios realizados en la interfaz de usuario*/
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        seleccionDeBotonesCuentas(jButton6);
        adminCuentas("actualizar");
    }//GEN-LAST:event_jButton6ActionPerformed

    //acción del botón "Aplicar" en la pestaña de la Apariencia para aplicar un tema a la app
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        LF= jList1.getSelectedValue();
        if(LF == null){
            JOptionPane.showMessageDialog(this, "Debe selecionar un Tema para cambiarlo",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(controladorConf.getTema().equals(LF)) return;
        JOptionPane.showMessageDialog(this, "<html>La aplicación debe reiniciarse para aplicar la nueva <b>Apariencia</b></html>",
                "Información", JOptionPane.INFORMATION_MESSAGE);
        controladorConf.aplicarTema(LF);
        cambioTema= true;
        String nombreSuperAdmin= ((Vista.Inicio)this.getOwner()).getNombreAdmin();
        gestionEventos.agregarEvento("Responsable: " + nombreSuperAdmin + "\n" + 
                "Lugar: Sistema\n" + "El superadministrador cambió el tema de apariencia del sistema a " + 
                LF);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    //cuando se escoge un tema en la lista de temas de la sección "Apariencia", se muestra una vista pequeña del tema
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        //<editor-fold defaultstate="collapsed" desc="vistas">
        switch(jList1.getSelectedValue()){
            case "Nimbus (Por defecto)" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/nimbus_small.jpg")));
            case "Metal" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/metal_small.jpg")));
            case "Motif/CDE" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/motif_small.jpg")));
            case "FlatLaf Darcula" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf Darcula_small.jpg")));
            case "FlatLaf Dark" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf Dark_small.jpg")));
            case "FlatLaf Light" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf Light_small.jpg")));
            case "FlatLaf IntelliJ" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf IntelliJ_small.jpg")));
            case "FlatLaf MacDark" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf MacDark_small.jpg")));
            case "FlatLaf MacLight" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf MacLight_small.jpg")));
            case "JTattoo Luna" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Luna_small.jpg")));
            case "JTattoo Acryl" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Acryl_small.jpg")));
            case "JTattoo Aero" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Aero_small.jpg")));
            case "JTattoo Aluminium" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Aluminium_small.jpg")));
            case "JTattoo Bernstein" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Bernstein_small.jpg")));
            case "JTattoo Fast" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Fast_small.jpg")));
            case "JTattoo Graphite" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Graphite_small.jpg")));
            case "JTattoo HiFi" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo HiFi_small.jpg")));
            case "JTattoo McWin" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo McWin_small.jpg")));
            case "JTattoo Mint" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Mint_small.jpg")));
            case "JTattoo Noire" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Noire_small.jpg")));
            case "JTattoo Smart" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Smart_small.jpg")));
            case "JTattoo Texture" -> jLabel5.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Texture_small.jpg")));
        }
        //</editor-fold>
    }//GEN-LAST:event_jList1MouseClicked

    //acción del botón "Resetear" para cargar valores por defecto de la configuración
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controladorConf.Reset();
        JOptionPane.showMessageDialog(this, "Valores por defecto cargados, el tema por defecto\n será cargado en el próximo renicio",
                "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    //muestra una vista grande de la ventana de la app cuando se da click sobre la vista más pequeña
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(!jList1.isSelectionEmpty()){
            //<editor-fold defaultstate="collapsed" desc="vistas">
            switch(jList1.getSelectedValue()){
                case "Nimbus (Por defecto)" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/nimbus.jpg")));
                case "Metal" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/metal.jpg")));
                case "Motif/CDE" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/motif.jpg")));
                case "FlatLaf Darcula" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf Darcula.jpg")));
                case "FlatLaf Dark" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf Dark.jpg")));
                case "FlatLaf Light" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf Light.jpg")));
                case "FlatLaf IntelliJ" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf IntelliJ.jpg")));
                case "FlatLaf MacDark" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf MacDark.jpg")));
                case "FlatLaf MacLight" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/FlatLaf MacLight.jpg")));
                case "JTattoo Luna" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Luna.jpg")));
                case "JTattoo Acryl" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Acryl.jpg")));
                case "JTattoo Aero" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Aero.jpg")));
                case "JTattoo Aluminium" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Aluminium.jpg")));
                case "JTattoo Bernstein" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Bernstein.jpg")));
                case "JTattoo Fast" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Fast.jpg")));
                case "JTattoo Graphite" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Graphite.jpg")));
                case "JTattoo HiFi" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo HiFi.jpg")));
                case "JTattoo McWin" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo McWin.jpg")));
                case "JTattoo Mint" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Mint.jpg")));
                case "JTattoo Noire" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Noire.jpg")));
                case "JTattoo Smart" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Smart.jpg")));
                case "JTattoo Texture" -> jLabel6.setIcon(new ImageIcon(getClass().getResource("/screenshots/JTattoo Texture.jpg")));
            }
            //</editor-fold>
            Vista.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            Vista.setModalityType(ModalityType.APPLICATION_MODAL);
            Vista.pack();
            Vista.setLocationRelativeTo(this);
            Vista.setVisible(true);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    //cierra la vista grande que se muestra cuando se da click sobre la vista más pequeña
    private void VistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VistaMouseClicked
        Vista.dispose();
    }//GEN-LAST:event_VistaMouseClicked

    public static void mostrarMSG(java.awt.Component padre, String mensaje){
        //<editor-fold defaultstate="collapsed" desc="muestra cuadro de mensaje como un tooltip que desaparece a los 3 segundos">
        JDialog msg= new JDialog();
        msg.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        msg.setModalityType(ModalityType.APPLICATION_MODAL);
        String[] msgSplit= mensaje.split("\n");
        for(int i= 0, max= 0, y= 0; i < msgSplit.length; i++){
            JLabel texto= new JLabel();
            texto.setText(msgSplit[i]);
            max= texto.getText().length() > max? texto.getText().length() : max;
            msg.setPreferredSize(new Dimension(max * 7, y += 30));
            msg.getContentPane().add(texto);
        }
        msg.setUndecorated(true);
        msg.getContentPane().setBackground(Color.ORANGE);
        msg.getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER));
        msg.pack();
        msg.setLocationRelativeTo(padre);
        new Thread(()->{
            try{
                Thread.sleep(3000);
                //esto es para mostrar un efecto fade off antes de desaparecer msg.
                float[] fadeValues= new float[]{0.8f, 0.6f, 0.4f, 0.2f};
                for(int i= 0; i < 4; i++){
                    msg.setOpacity(fadeValues[i]);
                    Thread.sleep(100);
                }
                msg.setOpacity(0);
            }
            catch(InterruptedException e){e.printStackTrace();}
            msg.dispose();
        }).start();
        msg.setVisible(true);
        //</editor-fold>
    }
    
    //esto es para definir el color del fondo y de las letras de los botónes
    //de las operaciones de las cuentas cuando se seleccionan y cuando no
    private void seleccionDeBotonesCuentas(JButton botonSelecionado){
        JButton[] botonesCuentas= new JButton[]{jButton3, jButton4, jButton5, jButton6};
        Color defaultBackgroundColor= new JButton().getBackground();
        Color defaultForegroundColor= new JButton().getForeground();
        for(JButton boton : botonesCuentas){
            if(boton == botonSelecionado){
                botonSelecionado.setBackground(jTable1.getSelectionBackground());
                botonSelecionado.setForeground(jTable1.getSelectionForeground());
            }
            else{
                boton.setBackground(defaultBackgroundColor);
                boton.setForeground(defaultForegroundColor);
            }
        }
    }
    
    //mostrar ventana de credenciales para crear una nueva cuenta o para cambiar las credenciales de una ya creada
    private void mostrarVentanaDeCredenciales(){
        jPasswordField1.setEchoChar('\u2022');
        if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire"))
            jLabel4.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye_b.png")));
        else jLabel4.setIcon(new ImageIcon(getClass().getResource("/Iconos/eye.png")));
        nuevaCuenta.pack();
        nuevaCuenta.setLocationRelativeTo(this);
        nuevaCuenta.setVisible(true);
    }
    
    private void adminCuentas(String operacion){
        DefaultTableModel tabla= (DefaultTableModel)jTable1.getModel();
        //<editor-fold defaultstate="collapsed" desc="las operaciones de la sección cuentas">
        if(operacion.equals("asignar")){
            controladorConf.adminCuentas(OpcionesConfig.GET_CUENTAS, null);
            for(Object[] cuenta : controladorConf.getCuentas()){
                Object[] rowData= new Object[]{cuenta[1], cuenta[2], cuenta[3]};
                tabla.addRow(rowData);
                //oculta las contraseñas en la tabla de las cuentas
                int lon= cuenta[2].toString().length();
                String password= "";
                for(int i= 0; i < lon; i++) password+= '\u2022';
                tabla.setValueAt(password, tabla.getRowCount() - 1, 1);
            }
            //esto es para el tamaño de las columnas
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(jTable1.getParent().getWidth() - 290);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
            //esto es para cuando se de click sobre el checkbox de la columna SuperAdmin.
            jTable1.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    //<editor-fold defaultstate="collapsed" desc="Código">
                    super.mousePressed(e);
                    Point coorMouse= e.getPoint();
                    for(int row= 0; row < jTable1.getRowCount(); row++){
                        int column= 0;
                        for(int col= 0; col < 3; col++)
                            if(jTable1.getColumnName(col).equals("SuperAdmin."))
                                column= col;
                        int coordX= jTable1.getCellRect(row, column, false).x + 40;
                        int coordY= jTable1.getCellRect(row, column, false).y + 5;
                        if(coorMouse.x > coordX && coorMouse.x < (coordX + 10) 
                                && coorMouse.y > coordY && coorMouse.y < (coordY + 10)){
                            boolean valor= (boolean)jTable1.getValueAt(row, column);
                            valor= !(valor == true);
                            //con la siguiente condición se garantiza que exista al menos 1 superadministrador
                            if(!valor){
                                int cantSuper= 0;
                                for(int i= 0; i < jTable1.getRowCount(); i++)
                                    if((boolean)jTable1.getValueAt(i, column))
                                        cantSuper+= 1;
                                if(cantSuper == 1){
                                    JOptionPane.showMessageDialog(null, "Debe de existir al menos un Superadministrador",
                                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                                    return;
                                }
                            }
                            //agrega el valor de superAdmin a la tabla
                            jTable1.setValueAt(valor, row, column);
                            /*actualiza la cuenta en la lista de cuentas en el controlador, algo parecido a lo que se hace
                            con "Cambiar credenciales"*/
                            String AdminName= tabla.getValueAt(row, 0).toString();
                            String password= controladorConf.getPasswordDe(AdminName);
                            boolean superAdmin= valor;
                            controladorConf.adminCuentas(OpcionesConfig.UPDATE_CUENTA, 
                                    new Object[]{AdminName, AdminName, password, superAdmin});
                            break;
                        }
                    }
                    //</editor-fold>
                }
            });
        }
        else if(operacion.equals("añadir")){
            jTextField1.setText("");
            jPasswordField1.setText("");
            jButton7.setText("Añadir");
            jButton7.setIcon(new ImageIcon(getClass().getResource("/Iconos/plus.png")));
            nuevaCuenta.setTitle("Nueva Cuenta");
            mostrarVentanaDeCredenciales();
        }
        else if(operacion.equals("eliminar")){
            int fila= jTable1.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(this, "Debe seleccionar una cuenta a eliminar"
                        , "Eliminar cuenta", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Object AdminName= tabla.getValueAt(fila, 0);
            controladorConf.adminCuentas(OpcionesConfig.ERASE_CUENTA, new Object[]{AdminName});
            tabla.removeRow(fila);
            mostrarMSG(this, "Cuenta eliminada");
        }
        else if(operacion.equals("credenciales")){
            int fila= jTable1.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(this, "Debe seleccionar una cuenta para cambiar sus credenciales"
                        , "Cambiar credenciales de la cuenta", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String AdminName= tabla.getValueAt(fila, 0).toString();
            jTextField1.setText(AdminName);
            jPasswordField1.setText(controladorConf.getPasswordDe(AdminName));
            jButton7.setText("Cambiar");
            jButton7.setIcon(new ImageIcon(getClass().getResource("/Iconos/actualización.png")));
            nuevaCuenta.setTitle("Cambiar Credenciales");
            mostrarVentanaDeCredenciales();
        }
        else if(operacion.equals("actualizar")){
            /*aunque se creen cuentas nuevas, se modifiquen las credenciales o se eliminen cuentas existentes,
            realmente lo que se hace es realizar esas operaciones a una lista de cuentas en el controlador,
            no se realizan en la base de datos, para que los cambios tengan efecto en la BD,
            se deben aplicar los cambios con el botón "Actualizar cambios"*/
            controladorConf.adminCuentas(OpcionesConfig.UPDATE_CUENTAS, null);
            if(controladorConf.getCambios()){
                String nombreSuperAdmin= ((Vista.Inicio)this.getOwner()).getNombreAdmin();
                gestionEventos.agregarEvento("Responsable: " + nombreSuperAdmin + "\n" + 
                        "Lugar: Sistema\n" + "El superadministrador realizó cambios en las cuentas");
                controladorConf.resetCambios();
            }
            mostrarMSG(this, "Los cambios realizados se han actualizado en la Base de datos");
        }
        //</editor-fold>
    }
    
    public boolean getCambioTema(){
        return cambioTema;
    }
    
    public String getLaf(){
        return LF;
    }
    
    private void cargarIconosBParaTemasN(){
        if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire")){
            jButton5.setIcon(new ImageIcon(getClass().getResource("/Iconos/credenciales_b.png")));
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Iconos/cuenta_b.png")));
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/Iconos/password_b.png")));
        }
    }
    
    private final OpcionesConfig controladorConf;
    private boolean cambioTema;
    private String LF;
    private final String tema= OpcionesConfig.cargarTema();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Vista;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JDialog nuevaCuenta;
    // End of variables declaration//GEN-END:variables
}
