/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.OpcionesConfig;
import Controlador.gestionEquipo;
import java.awt.Color;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author PC
 */
public class NuevoTelfVOIP extends javax.swing.JDialog {

    /**
     * Creates new form NuevoTelfVOIP
     * @param parent
     * @param modal
     */
    public NuevoTelfVOIP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorEq= new gestionEquipo();
        ID= -1;
        cargarIconosBParaTemasN();
    }
    
    public NuevoTelfVOIP(java.awt.Frame parent, boolean modal, Integer codigo) {
        super(parent, modal);
        this.codigo= codigo;
        initComponents();
        controladorEq= new gestionEquipo();
        cambiarModoAMod();
        asignarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agrega Nuevo Teléfono VOIP");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel10.setLayout(new java.awt.GridLayout(7, 0, 0, 15));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/numTelf.png"))); // NOI18N
        jLabel1.setText("Código:");
        jLabel1.setIconTextGap(20);
        jPanel2.add(jLabel1);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel2.add(jFormattedTextField1);

        jPanel10.add(jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lan.png"))); // NOI18N
        jLabel4.setText("IP:");
        jLabel4.setIconTextGap(20);
        jPanel5.add(jLabel4);

        jSpinner2.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner2);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText(".");
        jPanel6.add(jLabel5);

        jSpinner3.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner3);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText(".");
        jPanel6.add(jLabel6);

        jSpinner4.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner4);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText(".");
        jPanel6.add(jLabel7);

        jSpinner5.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner5StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner5);

        jPanel5.add(jPanel6);

        jPanel10.add(jPanel5);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inventario.png"))); // NOI18N
        jLabel2.setText("No. Inventario:");
        jLabel2.setIconTextGap(20);
        jPanel3.add(jLabel2);

        jSpinner1.setPreferredSize(new java.awt.Dimension(150, 30));
        jSpinner1.setValue(1);
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel3.add(jSpinner1);

        jPanel10.add(jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/departamento.png"))); // NOI18N
        jLabel8.setText("Departamento:");
        jLabel8.setIconTextGap(20);
        jPanel7.add(jLabel8);

        jTextField3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel7.add(jTextField3);

        jPanel10.add(jPanel7);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario_blue.png"))); // NOI18N
        jLabel3.setText("Usuario:");
        jLabel3.setIconTextGap(20);
        jPanel4.add(jLabel3);

        jTextField1.setForeground(java.awt.Color.GRAY);
        jTextField1.setText("Nombre");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel4.add(jTextField1);

        jTextField2.setForeground(java.awt.Color.GRAY);
        jTextField2.setText("Cargo");
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel4.add(jTextField2);

        jPanel10.add(jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/telf VOIP.png"))); // NOI18N
        jLabel9.setText("Propiedades:");
        jLabel9.setIconTextGap(20);
        jPanel8.add(jLabel9);

        jTextField4.setForeground(java.awt.Color.GRAY);
        jTextField4.setText("Marca");
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel8.add(jTextField4);

        jTextField5.setForeground(java.awt.Color.GRAY);
        jTextField5.setText("Modelo");
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel8.add(jTextField5);

        jTextField6.setForeground(java.awt.Color.GRAY);
        jTextField6.setText("No. Serie");
        jTextField6.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jPanel8.add(jTextField6);

        jPanel10.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/BD32x32.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setToolTipText("Registra el teléfono VOIP en la Base de Datos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1);

        jPanel10.add(jPanel9);

        jScrollPane1.setViewportView(jPanel10);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        placeHolderIn(jTextField1);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        placeHolderOut(jTextField1, "Nombre");
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        placeHolderIn(jTextField2);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        placeHolderOut(jTextField2, "Cargo");
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        placeHolderIn(jTextField4);
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        placeHolderOut(jTextField4, "Marca");
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        placeHolderIn(jTextField5);
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        placeHolderOut(jTextField5, "Modelo");
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        placeHolderIn(jTextField6);
    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        placeHolderOut(jTextField6, "No. Serie");
    }//GEN-LAST:event_jTextField6FocusLost

    //acción del botón "Guardar" el cuál valida y registra el equipo en la base de datos
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Validación">
        boolean vacios= false;
        JFormattedTextField formatField= new JFormattedTextField();
        JTextField textField= new JTextField();
        
        if(jFormattedTextField1.getText().contains(" ")){
            jFormattedTextField1.setBorder(new LineBorder(Color.red));
            vacios= true;
        }
        else jFormattedTextField1.setBorder(formatField.getBorder());
        
        Queue<JTextField> cola= new LinkedList<>(List.of(jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6));
        for(int i= 0; i < 6; i++){
            JTextField ref= cola.poll();
            if(ref.getText().equals("") || ref.getText().equals("Nombre") ||
                    ref.getText().equals("Cargo") || ref.getText().equals("Marca")||
                    ref.getText().equals("Modelo") || ref.getText().equals("No. Serie")){
                ref.setBorder(new LineBorder(Color.red));
                vacios= true;
            }
            else ref.setBorder(textField.getBorder());
        }
        
        if(vacios == true){
            JOptionPane.showMessageDialog(this, "Hay campos incompletos o vacios\nRevise los campos en rojo",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="Registro">
        Map<String, String> equipoNew= new HashMap();
        if(!ID.equals(-1))
            equipoNew.put("ID", ID.toString());
        equipoNew.put("Código", jFormattedTextField1.getText());
        String ip= jSpinner2.getValue().toString() + "." + jSpinner3.getValue().toString() + "." +
                jSpinner4.getValue().toString() + "." + jSpinner5.getValue().toString();
        equipoNew.put("IP", ip);
        equipoNew.put("NumInventario", jSpinner1.getValue().toString());
        equipoNew.put("Departamento", jTextField3.getText());
        equipoNew.put("NombreUsuario", jTextField1.getText());
        equipoNew.put("CargoUsuario", jTextField2.getText());
        equipoNew.put("Marca", jTextField4.getText());
        equipoNew.put("Modelo", jTextField5.getText());
        equipoNew.put("NumSerie", jTextField6.getText());
        equipoNew.put("CódigoAntiguo", codigo.toString());
        String estado= controladorEq.registrarVOIP(equipoNew);
        JOptionPane.showMessageDialog(this, estado, "Información", JOptionPane.INFORMATION_MESSAGE);
        if(estado.equals("Equipo correctamente registrado en la Base de datos") ||
                estado.equals("Equipo actualizado")){
            String nombreAdmin= ((Vista.Inicio)this.getOwner()).getNombreAdmin();
            if(estado.contains("registrado"))
                Controlador.gestionEventos.agregarEvento("Responsable: " + nombreAdmin + "\n" + 
                        "Lugar: Sistema\n" + "El administrador agregó un nuevo teléfono VOIP " + 
                        "con el código " + equipoNew.get("Código"));
            else if(controladorEq.getCambios())
                Controlador.gestionEventos.agregarEvento("Responsable: " + nombreAdmin + "\n" + 
                        "Lugar: Sistema\n" + "El administrador modificó los datos del teléfono VOIP " + 
                        "con el código " + equipoNew.get("Código"));
            this.dispose();
        }
        //</editor-fold>
    }//GEN-LAST:event_jButton1ActionPerformed

    //no permite números negativos y mas de 3 digitos en el spinner 1 de la ip
    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        Integer valor= (int)jSpinner2.getValue();
        if(valor < 0) jSpinner2.setValue(0);
        else if(valor > 255) jSpinner2.setValue(255);
    }//GEN-LAST:event_jSpinner2StateChanged

    //no permite números negativos y mas de 3 digitos en el spinner 2 de la ip
    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        Integer valor= (int)jSpinner3.getValue();
        if(valor < 0) jSpinner3.setValue(0);
        else if(valor > 255) jSpinner3.setValue(255);
    }//GEN-LAST:event_jSpinner3StateChanged

    //no permite números negativos y mas de 3 digitos en el spinner 3 de la ip
    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        Integer valor= (int)jSpinner4.getValue();
        if(valor < 0) jSpinner4.setValue(0);
        else if(valor > 255) jSpinner4.setValue(255);
    }//GEN-LAST:event_jSpinner4StateChanged

    //no permite números negativos y mas de 3 digitos en el spinner 4 de la ip
    private void jSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner5StateChanged
        Integer valor= (int)jSpinner5.getValue();
        if(valor < 0) jSpinner5.setValue(0);
        else if(valor > 255) jSpinner5.setValue(255);
    }//GEN-LAST:event_jSpinner5StateChanged

    //no permite números negativos en el inventario
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        Integer valor= (int)jSpinner1.getValue();
        if(valor < 1) jSpinner1.setValue(1);
    }//GEN-LAST:event_jSpinner1StateChanged

    //para que desaparezca el texto Placeholder cuando se da click sobre el textfield
    private void placeHolderIn(javax.swing.JTextField text){
        if(text.getForeground()== Color.GRAY){
            text.setText("");
            text.setForeground(new JTextField().getForeground());
        }
    }
    //para que aparezca el texto Placeholder correspondiente cuando se da click fuera del textfield
    private void placeHolderOut(javax.swing.JTextField text, String msg){
        if(text.getText().equals("")){
            text.setText(msg);
            text.setForeground(Color.GRAY);
        }
    }
    
    private void cargarIconosBParaTemasN(){
        String tema= OpcionesConfig.cargarTema();
        if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire")){
            jLabel4.setIcon(new ImageIcon(getClass().getResource("/Iconos/lan_b.png")));
            jLabel8.setIcon(new ImageIcon(getClass().getResource("/Iconos/departamento_b.png")));
        }
    }
    
    private void cambiarModoAMod(){
        this.setTitle("Administrar Teléfono VOIP");
        jTextField1.setToolTipText("Nombre");
        jTextField2.setToolTipText("Cargo");
        jTextField4.setToolTipText("Marca");
        jTextField5.setToolTipText("Modelo");
        jTextField6.setToolTipText("Número  de Serie");
        jButton1.setText("Actualizar");
        jButton1.setIcon(new ImageIcon(getClass().getResource("/Iconos/actualización.png")));
        jButton1.setToolTipText("Actualiza el teléfono VOIP en la Base de Datos");
    }
    
    private void asignarValores(){
        Map<String, String> voip= controladorEq.obtenerVOIP(codigo);
        if( voip == null) return;
        ID= Integer.valueOf(voip.get("ID"));
        JTextField text= new JTextField();
        jFormattedTextField1.setText(voip.get("Código"));
        String[] ip= voip.get("IP").split("\\.");
        jSpinner2.setValue(Integer.valueOf(ip[0]));
        jSpinner3.setValue(Integer.valueOf(ip[1]));
        jSpinner4.setValue(Integer.valueOf(ip[2]));
        jSpinner5.setValue(Integer.valueOf(ip[3]));
        jSpinner1.setValue(Integer.valueOf(voip.get("NumInventario")));
        jTextField3.setText(voip.get("Departamento"));
        jTextField1.setText(voip.get("NombreUsuario"));
        jTextField1.setForeground(text.getForeground());
        jTextField2.setText(voip.get("CargoUsuario"));
        jTextField2.setForeground(text.getForeground());
        jTextField4.setText(voip.get("Marca"));
        jTextField4.setForeground(text.getForeground());
        jTextField5.setText(voip.get("Modelo"));
        jTextField5.setForeground(text.getForeground());
        jTextField6.setText(voip.get("NumSerie"));
        jTextField6.setForeground(text.getForeground());
    }
    
    private final gestionEquipo controladorEq;
    private Integer ID;
    private Integer codigo;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
