/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.OpcionesConfig;
import Controlador.gestionEquipo;
import java.awt.Color;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author PC
 */
public class NuevoDispRED extends javax.swing.JDialog {

    /**
     * Creates new form NuevoDispRED
     * @param parent
     * @param modal
     */
    public NuevoDispRED(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorEq= new gestionEquipo();
        ID= -1;
        cargarIconosBParaTemasN();
    }
    
    public NuevoDispRED(java.awt.Frame parent, boolean modal, String ip) {
        super(parent, modal);
        this.ip= ip;
        initComponents();
        controladorEq= new gestionEquipo();
        cambiarModoAMod();
        asignarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Nuevo Dispositivo de RED");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(4, 0, 0, 15));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lan.png"))); // NOI18N
        jLabel1.setText("IP:");
        jLabel1.setIconTextGap(20);
        jPanel2.add(jLabel1);

        jSpinner1.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText(".");
        jPanel6.add(jLabel2);

        jSpinner2.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText(".");
        jPanel6.add(jLabel3);

        jSpinner3.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText(".");
        jPanel6.add(jLabel4);

        jSpinner4.setPreferredSize(new java.awt.Dimension(65, 30));
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });
        jPanel6.add(jSpinner4);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/router.png"))); // NOI18N
        jLabel5.setText("Tipo:");
        jLabel5.setIconTextGap(20);
        jPanel3.add(jLabel5);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Router", "Switch" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(60, 22));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel3.add(jComboBox1);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/marca y modelo.png"))); // NOI18N
        jLabel6.setText("Propiedades:");
        jLabel6.setIconTextGap(20);
        jPanel4.add(jLabel6);

        jTextField1.setForeground(java.awt.Color.GRAY);
        jTextField1.setText("Marca");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel4.add(jTextField1);

        jTextField2.setForeground(java.awt.Color.GRAY);
        jTextField2.setText("Modelo");
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel4.add(jTextField2);

        jTextField3.setForeground(java.awt.Color.GRAY);
        jTextField3.setText("No. Serie");
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel4.add(jTextField3);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/BD32x32.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setToolTipText("Registra el dispositivo en la Base de Datos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        placeHolderIn(jTextField1);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        placeHolderOut(jTextField1, "Marca");
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        placeHolderIn(jTextField2);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        placeHolderOut(jTextField2, "Modelo");
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        placeHolderIn(jTextField3);
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        placeHolderOut(jTextField3, "No. Serie");
    }//GEN-LAST:event_jTextField3FocusLost

    //no permite números negativos y mas de 3 digitos en el spinner 1 de la ip
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        Integer valor= (int)jSpinner1.getValue();
        if(valor < 0) jSpinner1.setValue(0);
        else if(valor > 255) jSpinner1.setValue(255);
    }//GEN-LAST:event_jSpinner1StateChanged

    //no permite números negativos y mas de 3 digitos en el spinner 2 de la ip
    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        Integer valor= (int)jSpinner2.getValue();
        if(valor < 0) jSpinner2.setValue(0);
        else if(valor > 255) jSpinner2.setValue(255);
    }//GEN-LAST:event_jSpinner2StateChanged

    //no permite números negativos y mas de 3 digitos en el spinner 3 de la ip
    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        Integer valor= (int)jSpinner3.getValue();
        if(valor < 0) jSpinner3.setValue(0);
        else if(valor > 255) jSpinner3.setValue(255);
    }//GEN-LAST:event_jSpinner3StateChanged

    //no permite números negativos y mas de 3 digitos en el spinner 4 de la ip
    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        Integer valor= (int)jSpinner4.getValue();
        if(valor < 0) jSpinner4.setValue(0);
        else if(valor > 255) jSpinner4.setValue(255);
    }//GEN-LAST:event_jSpinner4StateChanged

    //cuando se da click en el combobox cambia el icono de la etiqueta según el tipo de dispositivo
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String valor= jComboBox1.getSelectedItem().toString();
        if(valor.equals("Router"))
            jLabel5.setIcon(new ImageIcon(getClass().getResource("/Iconos/router.png")));
        else
            jLabel5.setIcon(new ImageIcon(getClass().getResource("/Iconos/switch.png")));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    //acción del botón "Guardar" el cuál valida y registra el equipo en la base de datos
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Validación">
        boolean vacios= false;
        JTextField textField= new JTextField();
        
        Queue<JTextField> cola= new LinkedList<>(List.of(jTextField1, jTextField2, jTextField3));
        for(int i= 0; i < 3; i++){
            JTextField ref= cola.poll();
            if(ref.getText().equals("Marca")|| ref.getText().equals("Modelo") || 
                    ref.getText().equals("No. Serie")){
                ref.setBorder(new LineBorder(Color.red));
                vacios= true;
            }
            else ref.setBorder(textField.getBorder());
        }
        
        if(vacios == true){
            JOptionPane.showMessageDialog(this, "Hay campos vacios\nRevise los campos en rojo",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="Registro">
        Map<String, String> equipoNew= new HashMap();
        if(!ID.equals(-1))
            equipoNew.put("ID", ID.toString());
        String ip= jSpinner1.getValue().toString() + "." + jSpinner2.getValue().toString() + "." +
                jSpinner3.getValue().toString() + "." + jSpinner4.getValue().toString();
        equipoNew.put("IP", ip);
        equipoNew.put("Tipo", jComboBox1.getSelectedItem().toString());
        equipoNew.put("Marca", jTextField1.getText());
        equipoNew.put("Modelo", jTextField2.getText());
        equipoNew.put("NumSerie", jTextField3.getText());
        equipoNew.put("IPAntigua", this.ip);
        String estado= controladorEq.registrarDispRED(equipoNew);
        JOptionPane.showMessageDialog(this, estado, "Información", JOptionPane.INFORMATION_MESSAGE);
        if(estado.equals("Equipo correctamente registrado en la Base de datos") ||
                estado.equals("Equipo actualizado")){
            String nombreAdmin= ((Vista.Inicio)this.getOwner()).getNombreAdmin();
            if(estado.contains("registrado"))
                Controlador.gestionEventos.agregarEvento("Responsable: " + nombreAdmin + "\n" + 
                        "Lugar: Sistema\n" + "El administrador agregó un nuevo " +
                        equipoNew.get("Tipo") + " con el ip " + equipoNew.get("IP"));
            else if(controladorEq.getCambios())
                Controlador.gestionEventos.agregarEvento("Responsable: " + nombreAdmin + "\n" + 
                        "Lugar: Sistema\n" + "El administrador modificó los datos del " + 
                        equipoNew.get("Tipo") + " con el ip " + equipoNew.get("IP"));
            this.dispose();
        }
        //</editor-fold>
    }//GEN-LAST:event_jButton1ActionPerformed

    //para que desaparezca el texto Placeholder cuando se da click sobre el textfield
    private void placeHolderIn(javax.swing.JTextField text){
        if(text.getForeground()== Color.GRAY){
            text.setText("");
            text.setForeground(new JTextField().getForeground());
        }
    }
    //para que aparezca el texto Placeholder correspondiente cuando se da click fuera del textfield
    private void placeHolderOut(javax.swing.JTextField text, String msg){
        if(text.getText().equals("")){
            text.setText(msg);
            text.setForeground(Color.GRAY);
        }
    }
    
    private void cargarIconosBParaTemasN(){
        String tema= OpcionesConfig.cargarTema();
        if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire"))
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Iconos/lan_b.png")));
    }
    
    private void cambiarModoAMod(){
        this.setTitle("Administrar Dispositivo de RED");
        jTextField1.setToolTipText("Marca");
        jTextField2.setToolTipText("Modelo");
        jTextField3.setToolTipText("Número  de Serie");
        jButton1.setText("Actualizar");
        jButton1.setIcon(new ImageIcon(getClass().getResource("/Iconos/actualización.png")));
        jButton1.setToolTipText("Actualiza el dispositivo en la Base de Datos");
    }
    
    private void asignarValores(){
        Map<String, String> disp= controladorEq.obtenerDispRed(ip);
        if( disp == null) return;
        ID= Integer.valueOf(disp.get("ID"));
        JTextField text= new JTextField();
        String[] IP= disp.get("IP").split("\\.");
        jSpinner1.setValue(Integer.valueOf(IP[0]));
        jSpinner2.setValue(Integer.valueOf(IP[1]));
        jSpinner3.setValue(Integer.valueOf(IP[2]));
        jSpinner4.setValue(Integer.valueOf(IP[3]));
        jComboBox1.setSelectedItem(disp.get("Tipo"));
        jTextField1.setText(disp.get("Marca"));
        jTextField1.setForeground(text.getForeground());
        jTextField2.setText(disp.get("Modelo"));
        jTextField2.setForeground(text.getForeground());
        jTextField3.setText(disp.get("NumSerie"));
        jTextField3.setForeground(text.getForeground());
    }
    
    private final gestionEquipo controladorEq;
    private Integer ID;
    private String ip;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
