/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.gestionEquipo;
import java.awt.Color;
import java.text.ParseException;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author PC
 */
public class NuevoTelfMovil extends javax.swing.JDialog {

    /**
     * Creates new form NuevoTelfMovil
     * @param parent
     * @param modal
     */
    public NuevoTelfMovil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorEq= new gestionEquipo();
        ID= -1;
    }
    
    public NuevoTelfMovil(java.awt.Frame parent, boolean modal, String numTelf) {
        super(parent, modal);
        this.numTelf= numTelf;
        initComponents();
        controladorEq= new gestionEquipo();
        cambiarModoAMod();
        asignarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Nuevo Teléfono Móvil");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.GridLayout(6, 0, 0, 15));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/numTelf.png"))); // NOI18N
        jLabel1.setText("Número Telefónico:");
        jLabel1.setIconTextGap(20);
        jPanel2.add(jLabel1);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel2.add(jFormattedTextField1);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/email.png"))); // NOI18N
        jLabel2.setText("email:");
        jLabel2.setIconTextGap(20);
        jPanel3.add(jLabel2);

        jTextField1.setForeground(java.awt.Color.GRAY);
        jTextField1.setText("correo_electronico@gmail.com");
        jTextField1.setPreferredSize(new java.awt.Dimension(250, 30));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel3.add(jTextField1);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario_blue.png"))); // NOI18N
        jLabel3.setText("Usuario:");
        jLabel3.setIconTextGap(20);
        jPanel4.add(jLabel3);

        jTextField2.setForeground(java.awt.Color.GRAY);
        jTextField2.setText("Nombre");
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel4.add(jTextField2);

        jTextField3.setForeground(java.awt.Color.GRAY);
        jTextField3.setText("Cargo");
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel4.add(jTextField3);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PIN.png"))); // NOI18N
        jLabel4.setText("Seguridad:");
        jLabel4.setIconTextGap(20);
        jPanel5.add(jLabel4);

        jFormattedTextField4.setForeground(java.awt.Color.GRAY);
        jFormattedTextField4.setText("PIN");
        jFormattedTextField4.setPreferredSize(new java.awt.Dimension(60, 30));
        jFormattedTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField4FocusLost(evt);
            }
        });
        jPanel5.add(jFormattedTextField4);

        jFormattedTextField3.setForeground(java.awt.Color.GRAY);
        jFormattedTextField3.setText("PUK");
        jFormattedTextField3.setPreferredSize(new java.awt.Dimension(100, 30));
        jFormattedTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField3FocusLost(evt);
            }
        });
        jPanel5.add(jFormattedTextField3);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/MMCel.png"))); // NOI18N
        jLabel5.setText("Propiedades:");
        jLabel5.setIconTextGap(20);
        jPanel6.add(jLabel5);

        jTextField4.setForeground(java.awt.Color.GRAY);
        jTextField4.setText("Marca");
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel6.add(jTextField4);

        jTextField5.setForeground(java.awt.Color.GRAY);
        jTextField5.setText("Modelo");
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel6.add(jTextField5);

        jTextField6.setForeground(java.awt.Color.GRAY);
        jTextField6.setText("No. Serie");
        jTextField6.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jPanel6.add(jTextField6);

        jPanel1.add(jPanel6);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/BD32x32.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setToolTipText("Registra el móvil en la Base de Datos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        placeHolderIn(jTextField1);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        placeHolderOut(jTextField1, "correo_electronico@gmail.com");
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        placeHolderIn(jTextField2);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        placeHolderOut(jTextField2, "Nombre");
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        placeHolderIn(jTextField3);
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        placeHolderOut(jTextField3, "Cargo");
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        placeHolderIn(jTextField4);
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        placeHolderOut(jTextField4, "Marca");
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        placeHolderIn(jTextField5);
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        placeHolderOut(jTextField5, "Modelo");
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        placeHolderIn(jTextField6);
    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        placeHolderOut(jTextField6, "No. Serie");
    }//GEN-LAST:event_jTextField6FocusLost

    //cuando se da click sobre PIN, desaparece el texto y se permite introducir solo 4 dígitos
    private void jFormattedTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField4FocusGained
        jFormattedTextField4.setText("");
        jFormattedTextField4.setForeground(new JFormattedTextField().getForeground());
        try{
            jFormattedTextField4.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("####")));
        }catch(ParseException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jFormattedTextField4FocusGained

    //cuando se da click sobre PUK, desaparece el texto y se permite introducir solo 8 dígitos
    private void jFormattedTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField3FocusGained
        jFormattedTextField3.setText("");
        jFormattedTextField3.setForeground(new JFormattedTextField().getForeground());
        try{
            jFormattedTextField3.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("########")));
        }catch(ParseException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jFormattedTextField3FocusGained

    //si en PIN no se escriben los 4 dígitos se vuelve a colocar el texto "PIN"
    private void jFormattedTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField4FocusLost
        if(jFormattedTextField4.getText().contains(" ")){
            jFormattedTextField4.setFormatterFactory(null);
            jFormattedTextField4.setText("PIN");
            jFormattedTextField4.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jFormattedTextField4FocusLost

    //si en PUK no se escriben los 8 dígitos se vuelve a colocar el texto "PUK"
    private void jFormattedTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField3FocusLost
        if(jFormattedTextField3.getText().contains(" ")){
            jFormattedTextField3.setFormatterFactory(null);
            jFormattedTextField3.setText("PUK");
            jFormattedTextField3.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jFormattedTextField3FocusLost

    //acción del botón "Guardar" el cuál valida y registra el equipo en la base de datos
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Validación">
        boolean vacios= false;
        JFormattedTextField formatField= new JFormattedTextField();
        JTextField textField= new JTextField();
        
        if(jFormattedTextField1.getText() == null ||
                !jFormattedTextField1.getText().matches("\\d\\d[ ]\\d\\d[ ]\\d\\d[ ]\\d\\d")){
            jFormattedTextField1.setBorder(new LineBorder(Color.red));
            vacios= true;
        }
        else jFormattedTextField1.setBorder(formatField.getBorder());
        
        if(!jTextField1.getText().matches(".*[@].*[.].*") ||
                jTextField1.getText().equals("correo_electronico@gmail.com")){
            jTextField1.setBorder(new LineBorder(Color.red));
            vacios= true;
        }
        else jTextField1.setBorder(textField.getBorder());
        
        if(jFormattedTextField3.getText().equals("PUK")){
            jFormattedTextField3.setBorder(new LineBorder(Color.red));
            vacios= true;
        }
        else jFormattedTextField3.setBorder(formatField.getBorder());
        
        if(jFormattedTextField4.getText().equals("PIN")){
            jFormattedTextField4.setBorder(new LineBorder(Color.red));
            vacios= true;
        }
        else jFormattedTextField4.setBorder(formatField.getBorder());
        
        Queue<JTextField> cola= new LinkedList<>(List.of(jTextField2, jTextField3, jTextField4, jTextField5, jTextField6));
        for(int i= 0; i < 5; i++){
            JTextField ref= cola.poll();
            if(ref.getText().equals("Nombre") ||
                    ref.getText().equals("Cargo") || ref.getText().equals("Marca")||
                    ref.getText().equals("Modelo") || ref.getText().equals("No. Serie")){
                ref.setBorder(new LineBorder(Color.red));
                vacios= true;
            }
            else ref.setBorder(textField.getBorder());
        }
        
        if(vacios == true){
            JOptionPane.showMessageDialog(this, "Hay campos incompletos o vacios\nRevise los campos en rojo",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="Registro">
        Map<String, String> equipoNew= new HashMap();
        if(!ID.equals(-1))
            equipoNew.put("ID", ID.toString());
        equipoNew.put("NumTelf", jFormattedTextField1.getText());
        equipoNew.put("email", jTextField1.getText());
        equipoNew.put("NombreUsuario", jTextField2.getText());
        equipoNew.put("CargoUsuario", jTextField3.getText());
        equipoNew.put("PIN", jFormattedTextField4.getText());
        equipoNew.put("PUK", jFormattedTextField3.getText());
        equipoNew.put("Marca", jTextField4.getText());
        equipoNew.put("Modelo", jTextField5.getText());
        equipoNew.put("NumSerie", jTextField6.getText());
        equipoNew.put("NumTelfAntiguo", numTelf);
        String estado= controladorEq.registrarMovil(equipoNew);
        JOptionPane.showMessageDialog(this, estado, "Información", JOptionPane.INFORMATION_MESSAGE);
        if(estado.equals("Equipo correctamente registrado en la Base de datos") ||
                estado.equals("Equipo actualizado")){
            String nombreAdmin= ((Vista.Inicio)this.getOwner()).getNombreAdmin();
            if(estado.contains("registrado"))
                Controlador.gestionEventos.agregarEvento("Responsable: " + nombreAdmin + "\n" + 
                        "Lugar: Sistema\n" + "El administrador agregó un nuevo teléfono móvil " + 
                        "con el número " + equipoNew.get("NumTelf"));
            else if(controladorEq.getCambios())
                Controlador.gestionEventos.agregarEvento("Responsable: " + nombreAdmin + "\n" + 
                        "Lugar: Sistema\n" + "El administrador modificó los datos del teléfono móvil " + 
                        "con el número " + equipoNew.get("NumTelf"));
            this.dispose();
        }
        //</editor-fold>
    }//GEN-LAST:event_jButton1ActionPerformed

    //para que desaparezca el texto Placeholder cuando se da click sobre el textfield
    private void placeHolderIn(javax.swing.JTextField text){
        if(text.getForeground()== Color.GRAY){
            text.setText("");
            text.setForeground(new JTextField().getForeground());
        }
    }
    //para que aparezca el texto Placeholder correspondiente cuando se da click fuera del textfield
    private void placeHolderOut(javax.swing.JTextField text, String msg){
        if(text.getText().equals("")){
            text.setText(msg);
            text.setForeground(Color.GRAY);
        }
    }
    
    private void cambiarModoAMod(){
        this.setTitle("Administrar Teléfono Móvil");
        jTextField2.setToolTipText("Nombre");
        jTextField3.setToolTipText("Cargo");
        jFormattedTextField4.setToolTipText("PIN");
        jFormattedTextField3.setToolTipText("PUK");
        jTextField4.setToolTipText("Marca");
        jTextField5.setToolTipText("Modelo");
        jTextField6.setToolTipText("Número  de Serie");
        jButton1.setText("Actualizar");
        jButton1.setIcon(new ImageIcon(getClass().getResource("/Iconos/actualización.png")));
        jButton1.setToolTipText("Actualiza el móvil en la Base de Datos");
    }
    
    private void asignarValores(){
        Map<String, String> movil= controladorEq.obtenerMovil(numTelf);
        if( movil == null) return;
        ID= Integer.valueOf(movil.get("ID"));
        JFormattedTextField format= new JFormattedTextField();
        JTextField text= new JTextField();
        jFormattedTextField1.setText(movil.get("NumTelf"));
        jTextField1.setText(movil.get("email"));
        jTextField1.setForeground(text.getForeground());
        jTextField2.setText(movil.get("NombreUsuario"));
        jTextField2.setForeground(text.getForeground());
        jTextField3.setText(movil.get("CargoUsuario"));
        jTextField3.setForeground(text.getForeground());
        jFormattedTextField4.setText(movil.get("PIN"));
        jFormattedTextField4.setForeground(format.getForeground());
        jFormattedTextField3.setText(movil.get("PUK"));
        jFormattedTextField3.setForeground(format.getForeground());
        jTextField4.setText(movil.get("Marca"));
        jTextField4.setForeground(text.getForeground());
        jTextField5.setText(movil.get("Modelo"));
        jTextField5.setForeground(text.getForeground());
        jTextField6.setText(movil.get("NumSerie"));
        jTextField6.setForeground(text.getForeground());
    }

    private final gestionEquipo controladorEq;
    private Integer ID;
    private String numTelf;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
