/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.OpcionesConfig;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import Controlador.gestionEquipo;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author PC
 */
public class nuevaComputadora extends javax.swing.JDialog {

    /**
     * Creates new form nuevaComputadora
     * @param parent
     * @param modal
     */
    public nuevaComputadora(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarIconosBParaTemasN();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Nueva Computadora");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 96));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 4000));
        jPanel1.setLayout(new java.awt.GridLayout(25, 0, 0, 15));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nombre.png"))); // NOI18N
        jLabel7.setText("Nombre del equipo (RED):");
        jLabel7.setIconTextGap(20);
        jPanel7.add(jLabel7);

        jTextField3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel7.add(jTextField3);

        jPanel1.add(jPanel7);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PC.png"))); // NOI18N
        jLabel27.setText("Tipo:");
        jLabel27.setIconTextGap(20);
        jPanel3.add(jLabel27);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Laptop", "Servidor" }));
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });
        jPanel3.add(jComboBox6);

        jPanel1.add(jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 35));

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lan.png"))); // NOI18N
        jLabel2.setText("IP:");
        jLabel2.setIconTextGap(20);
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 60));
        jPanel5.add(jLabel2);

        jSpinner1.setPreferredSize(new java.awt.Dimension(64, 28));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel5.add(jSpinner1);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText(".");
        jPanel5.add(jLabel3);

        jSpinner3.setPreferredSize(new java.awt.Dimension(64, 28));
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });
        jPanel5.add(jSpinner3);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText(".");
        jPanel5.add(jLabel5);

        jSpinner4.setPreferredSize(new java.awt.Dimension(64, 28));
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });
        jPanel5.add(jSpinner4);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText(".");
        jPanel5.add(jLabel4);

        jSpinner2.setMinimumSize(new java.awt.Dimension(63, 22));
        jSpinner2.setPreferredSize(new java.awt.Dimension(64, 28));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        jPanel5.add(jSpinner2);

        jPanel1.add(jPanel5);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario.png"))); // NOI18N
        jLabel1.setText("Usuario:");
        jLabel1.setIconTextGap(20);
        jPanel4.add(jLabel1);

        jTextField1.setForeground(java.awt.Color.GRAY);
        jTextField1.setText("Nombre");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel4.add(jTextField1);

        jTextField56.setForeground(java.awt.Color.GRAY);
        jTextField56.setText("Cargo");
        jTextField56.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField56.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField56FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField56FocusLost(evt);
            }
        });
        jPanel4.add(jTextField56);

        jPanel1.add(jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/departamento.png"))); // NOI18N
        jLabel6.setText("Departamento:");
        jLabel6.setIconTextGap(20);
        jPanel6.add(jLabel6);

        jTextField2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel6.add(jTextField2);

        jPanel1.add(jPanel6);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sello.png"))); // NOI18N
        jLabel9.setText("No. Sello:");
        jLabel9.setIconTextGap(20);
        jPanel9.add(jLabel9);

        jSpinner5.setPreferredSize(new java.awt.Dimension(80, 28));
        jSpinner5.setValue(1);
        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner5StateChanged(evt);
            }
        });
        jPanel9.add(jSpinner5);

        jPanel1.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/llavero.png"))); // NOI18N
        jLabel10.setText("No. Llavero:");
        jLabel10.setIconTextGap(20);
        jPanel10.add(jLabel10);

        jSpinner6.setPreferredSize(new java.awt.Dimension(80, 28));
        jSpinner6.setValue(1);
        jSpinner6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner6StateChanged(evt);
            }
        });
        jPanel10.add(jSpinner6);

        jPanel1.add(jPanel10);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/SO.png"))); // NOI18N
        jLabel8.setText("Sistema Operativo:");
        jLabel8.setIconTextGap(20);
        jPanel8.add(jLabel8);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Windows XP", "Windows 7", "Windows 8.1", "Windows 10", "Windows 11", "Linux" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel8.add(jComboBox1);

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Professional", "Media Center", "64 bit" }));
        jPanel8.add(jComboBox2);

        jTextField4.setForeground(Color.GRAY);
        jTextField4.setText("Versión");
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel8.add(jTextField4);

        jPanel1.add(jPanel8);

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CPU.png"))); // NOI18N
        jLabel11.setText("CPU:");
        jLabel11.setIconTextGap(20);
        jPanel11.add(jLabel11);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEL", "AMD" }));
        jPanel11.add(jComboBox3);

        jTextField5.setForeground(Color.GRAY);
        jTextField5.setText("Nombre");
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel11.add(jTextField5);

        jPanel1.add(jPanel11);

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/RAM.png"))); // NOI18N
        jLabel13.setText("RAM:");
        jLabel13.setIconTextGap(20);
        jPanel13.add(jLabel13);

        jTextField9.setForeground(Color.GRAY);
        jTextField9.setText("Marca");
        jTextField9.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jPanel13.add(jTextField9);

        jTextField10.setForeground(Color.GRAY);
        jTextField10.setText("Modelo");
        jTextField10.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jPanel13.add(jTextField10);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 GB", "4 GB", "8 GB", "16 GB", "32 GB", "64 GB" }));
        jPanel13.add(jComboBox4);

        jPanel1.add(jPanel13);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/motherboard.png"))); // NOI18N
        jLabel12.setText("Motherboard:");
        jLabel12.setIconTextGap(20);
        jPanel12.add(jLabel12);

        jTextField6.setForeground(Color.GRAY);
        jTextField6.setText("Marca");
        jTextField6.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jPanel12.add(jTextField6);

        jTextField7.setForeground(Color.GRAY);
        jTextField7.setText("Modelo");
        jTextField7.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jPanel12.add(jTextField7);

        jTextField8.setForeground(Color.GRAY);
        jTextField8.setText("No. Serie");
        jTextField8.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jPanel12.add(jTextField8);

        jPanel1.add(jPanel12);

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disco duro.png"))); // NOI18N
        jLabel14.setText("Disco Duro:");
        jLabel14.setIconTextGap(20);
        jPanel14.add(jLabel14);

        jTextField11.setForeground(Color.GRAY);
        jTextField11.setText("Marca");
        jTextField11.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField11FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jPanel14.add(jTextField11);

        jTextField12.setForeground(Color.GRAY);
        jTextField12.setText("Modelo");
        jTextField12.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField12FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });
        jPanel14.add(jTextField12);

        jTextField13.setForeground(Color.GRAY);
        jTextField13.setText("No. Serie");
        jTextField13.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField13FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });
        jPanel14.add(jTextField13);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "120 GB", "240 GB", "320 GB", "500 GB", "1 TB", "2 TB", "4 TB", "6 TB", "8 TB" }));
        jPanel14.add(jComboBox5);

        jPanel1.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CD-DVD.png"))); // NOI18N
        jLabel15.setText("Lector CD/DVD:");
        jLabel15.setIconTextGap(20);
        jPanel15.add(jLabel15);

        jTextField14.setForeground(Color.GRAY);
        jTextField14.setText("Marca");
        jTextField14.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField14FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField14FocusLost(evt);
            }
        });
        jPanel15.add(jTextField14);

        jTextField15.setForeground(Color.GRAY);
        jTextField15.setText("Modelo");
        jTextField15.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField15FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField15FocusLost(evt);
            }
        });
        jPanel15.add(jTextField15);

        jTextField16.setForeground(Color.GRAY);
        jTextField16.setText("No. Serie");
        jTextField16.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField16FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField16FocusLost(evt);
            }
        });
        jPanel15.add(jTextField16);

        jPanel1.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fuente.png"))); // NOI18N
        jLabel16.setText("Fuente:");
        jLabel16.setIconTextGap(20);
        jPanel16.add(jLabel16);

        jTextField17.setForeground(Color.GRAY);
        jTextField17.setText("Marca");
        jTextField17.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField17FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField17FocusLost(evt);
            }
        });
        jPanel16.add(jTextField17);

        jTextField18.setForeground(Color.GRAY);
        jTextField18.setText("Modelo");
        jTextField18.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField18FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField18FocusLost(evt);
            }
        });
        jPanel16.add(jTextField18);

        jTextField19.setForeground(Color.GRAY);
        jTextField19.setText("No. Serie");
        jTextField19.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField19FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField19FocusLost(evt);
            }
        });
        jPanel16.add(jTextField19);

        jPanel1.add(jPanel16);

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Teclado.png"))); // NOI18N
        jLabel17.setText("Teclado:");
        jLabel17.setIconTextGap(20);
        jPanel17.add(jLabel17);

        jTextField20.setForeground(Color.GRAY);
        jTextField20.setText("Marca");
        jTextField20.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField20FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField20FocusLost(evt);
            }
        });
        jPanel17.add(jTextField20);

        jTextField21.setForeground(Color.GRAY);
        jTextField21.setText("Modelo");
        jTextField21.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField21FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField21FocusLost(evt);
            }
        });
        jPanel17.add(jTextField21);

        jTextField22.setForeground(Color.GRAY);
        jTextField22.setText("No. Serie");
        jTextField22.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField22FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField22FocusLost(evt);
            }
        });
        jPanel17.add(jTextField22);

        jPanel1.add(jPanel17);

        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mouse.png"))); // NOI18N
        jLabel18.setText("Mouse:");
        jLabel18.setIconTextGap(20);
        jPanel18.add(jLabel18);

        jTextField23.setForeground(Color.GRAY);
        jTextField23.setText("Marca");
        jTextField23.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField23.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField23FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField23FocusLost(evt);
            }
        });
        jPanel18.add(jTextField23);

        jTextField24.setForeground(Color.GRAY);
        jTextField24.setText("Modelo");
        jTextField24.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField24FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField24FocusLost(evt);
            }
        });
        jPanel18.add(jTextField24);

        jTextField25.setForeground(Color.GRAY);
        jTextField25.setText("No. Serie");
        jTextField25.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField25.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField25FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField25FocusLost(evt);
            }
        });
        jPanel18.add(jTextField25);

        jPanel1.add(jPanel18);

        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bocinas.png"))); // NOI18N
        jLabel19.setText("Bocinas:");
        jLabel19.setIconTextGap(20);
        jPanel19.add(jLabel19);

        jTextField26.setForeground(Color.GRAY);
        jTextField26.setText("Marca");
        jTextField26.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField26.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField26FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField26FocusLost(evt);
            }
        });
        jPanel19.add(jTextField26);

        jTextField27.setForeground(Color.GRAY);
        jTextField27.setText("Modelo");
        jTextField27.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField27.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField27FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField27FocusLost(evt);
            }
        });
        jPanel19.add(jTextField27);

        jTextField28.setForeground(Color.GRAY);
        jTextField28.setText("No. Serie");
        jTextField28.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField28.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField28FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField28FocusLost(evt);
            }
        });
        jPanel19.add(jTextField28);

        jPanel1.add(jPanel19);

        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 35));

        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disquete.png"))); // NOI18N
        jLabel20.setText("Lector 3 1/2:");
        jLabel20.setIconTextGap(20);
        jPanel20.add(jLabel20);

        jTextField29.setForeground(Color.GRAY);
        jTextField29.setText("Marca");
        jTextField29.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField29.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField29FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField29FocusLost(evt);
            }
        });
        jPanel20.add(jTextField29);

        jTextField30.setForeground(Color.GRAY);
        jTextField30.setText("Modelo");
        jTextField30.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField30.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField30FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField30FocusLost(evt);
            }
        });
        jPanel20.add(jTextField30);

        jTextField31.setForeground(Color.GRAY);
        jTextField31.setText("No. Serie");
        jTextField31.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField31.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField31FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField31FocusLost(evt);
            }
        });
        jPanel20.add(jTextField31);

        jPanel1.add(jPanel20);

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/chasis.png"))); // NOI18N
        jLabel21.setText("Chasis:");
        jLabel21.setIconTextGap(20);
        jPanel21.add(jLabel21);

        jTextField32.setForeground(Color.GRAY);
        jTextField32.setText("Marca");
        jTextField32.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField32.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField32FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField32FocusLost(evt);
            }
        });
        jPanel21.add(jTextField32);

        jTextField33.setForeground(Color.GRAY);
        jTextField33.setText("Modelo");
        jTextField33.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField33.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField33FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField33FocusLost(evt);
            }
        });
        jPanel21.add(jTextField33);

        jTextField34.setForeground(Color.GRAY);
        jTextField34.setText("No. Serie");
        jTextField34.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField34.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField34FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField34FocusLost(evt);
            }
        });
        jPanel21.add(jTextField34);

        jTextField50.setForeground(Color.GRAY);
        jTextField50.setText("No. Inventario");
        jTextField50.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField50.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField50FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField50FocusLost(evt);
            }
        });
        jTextField50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField50KeyReleased(evt);
            }
        });
        jPanel21.add(jTextField50);

        jPanel1.add(jPanel21);

        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/monitor.png"))); // NOI18N
        jLabel22.setText("Monitor:");
        jLabel22.setIconTextGap(20);
        jPanel22.add(jLabel22);

        jTextField35.setForeground(Color.GRAY);
        jTextField35.setText("Marca");
        jTextField35.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField35.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField35FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField35FocusLost(evt);
            }
        });
        jPanel22.add(jTextField35);

        jTextField36.setForeground(Color.GRAY);
        jTextField36.setText("Modelo");
        jTextField36.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField36.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField36FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField36FocusLost(evt);
            }
        });
        jPanel22.add(jTextField36);

        jTextField37.setForeground(Color.GRAY);
        jTextField37.setText("No. Serie");
        jTextField37.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField37.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField37FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField37FocusLost(evt);
            }
        });
        jPanel22.add(jTextField37);

        jTextField51.setForeground(Color.GRAY);
        jTextField51.setText("No. Inventario");
        jTextField51.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField51.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField51FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField51FocusLost(evt);
            }
        });
        jTextField51.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField51KeyReleased(evt);
            }
        });
        jPanel22.add(jTextField51);

        jPanel1.add(jPanel22);

        jPanel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        jLabel23.setForeground(new java.awt.Color(0, 153, 0));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/UPS.png"))); // NOI18N
        jLabel23.setText("UPS:");
        jLabel23.setIconTextGap(20);
        jPanel23.add(jLabel23);

        jTextField38.setForeground(Color.GRAY);
        jTextField38.setText("Marca");
        jTextField38.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField38.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField38FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField38FocusLost(evt);
            }
        });
        jPanel23.add(jTextField38);

        jTextField39.setForeground(Color.GRAY);
        jTextField39.setText("Modelo");
        jTextField39.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField39.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField39FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField39FocusLost(evt);
            }
        });
        jPanel23.add(jTextField39);

        jTextField40.setForeground(Color.GRAY);
        jTextField40.setText("No. Serie");
        jTextField40.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField40.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField40FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField40FocusLost(evt);
            }
        });
        jPanel23.add(jTextField40);

        jTextField52.setForeground(Color.GRAY);
        jTextField52.setText("No. Inventario");
        jTextField52.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField52.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField52FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField52FocusLost(evt);
            }
        });
        jTextField52.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField52KeyReleased(evt);
            }
        });
        jPanel23.add(jTextField52);

        jPanel1.add(jPanel23);

        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel24.setForeground(new java.awt.Color(0, 153, 0));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/impresora.png"))); // NOI18N
        jLabel24.setText("Impresora:");
        jLabel24.setIconTextGap(20);
        jPanel24.add(jLabel24);

        jTextField41.setForeground(Color.GRAY);
        jTextField41.setText("Marca");
        jTextField41.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField41.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField41FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField41FocusLost(evt);
            }
        });
        jPanel24.add(jTextField41);

        jTextField42.setForeground(Color.GRAY);
        jTextField42.setText("Modelo");
        jTextField42.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField42.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField42FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField42FocusLost(evt);
            }
        });
        jPanel24.add(jTextField42);

        jTextField43.setForeground(Color.GRAY);
        jTextField43.setText("No. Serie");
        jTextField43.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField43.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField43FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField43FocusLost(evt);
            }
        });
        jPanel24.add(jTextField43);

        jTextField53.setForeground(Color.GRAY);
        jTextField53.setText("No. Inventario");
        jTextField53.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField53.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField53FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField53FocusLost(evt);
            }
        });
        jTextField53.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField53KeyReleased(evt);
            }
        });
        jPanel24.add(jTextField53);

        jPanel1.add(jPanel24);

        jPanel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/scanner.png"))); // NOI18N
        jLabel25.setText("Scanner:");
        jLabel25.setIconTextGap(20);
        jPanel25.add(jLabel25);

        jTextField44.setForeground(Color.GRAY);
        jTextField44.setText("Marca");
        jTextField44.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField44.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField44FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField44FocusLost(evt);
            }
        });
        jPanel25.add(jTextField44);

        jTextField45.setForeground(Color.GRAY);
        jTextField45.setText("Modelo");
        jTextField45.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField45.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField45FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField45FocusLost(evt);
            }
        });
        jPanel25.add(jTextField45);

        jTextField46.setForeground(Color.GRAY);
        jTextField46.setText("No. Serie");
        jTextField46.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField46.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField46FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField46FocusLost(evt);
            }
        });
        jPanel25.add(jTextField46);

        jTextField54.setForeground(Color.GRAY);
        jTextField54.setText("No. Inventario");
        jTextField54.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField54.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField54FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField54FocusLost(evt);
            }
        });
        jTextField54.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField54KeyReleased(evt);
            }
        });
        jPanel25.add(jTextField54);

        jPanel1.add(jPanel25);

        jPanel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        jLabel26.setForeground(new java.awt.Color(0, 153, 0));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fotocopy.png"))); // NOI18N
        jLabel26.setText("Fotocopiadora:");
        jLabel26.setIconTextGap(20);
        jPanel26.add(jLabel26);

        jTextField47.setForeground(Color.GRAY);
        jTextField47.setText("Marca");
        jTextField47.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField47.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField47FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField47FocusLost(evt);
            }
        });
        jPanel26.add(jTextField47);

        jTextField48.setForeground(Color.GRAY);
        jTextField48.setText("Modelo");
        jTextField48.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField48.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField48FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField48FocusLost(evt);
            }
        });
        jPanel26.add(jTextField48);

        jTextField49.setForeground(Color.GRAY);
        jTextField49.setText("No. Serie");
        jTextField49.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField49.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField49FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField49FocusLost(evt);
            }
        });
        jPanel26.add(jTextField49);

        jTextField55.setForeground(Color.GRAY);
        jTextField55.setText("No. Inventario");
        jTextField55.setPreferredSize(new java.awt.Dimension(150, 30));
        jTextField55.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField55FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField55FocusLost(evt);
            }
        });
        jTextField55.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField55KeyReleased(evt);
            }
        });
        jPanel26.add(jTextField55);

        jPanel1.add(jPanel26);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/BD32x32.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setToolTipText("Registra la computadora en la Base de Datos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setIconTextGap(10);
        jButton1.setPreferredSize(new java.awt.Dimension(115, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        jPanel2.add(jButton1, gridBagConstraints);

        jPanel1.add(jPanel2);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //para que desaparezca el texto Placeholder cuando se da click sobre el textfield
    private void placeHolderIn(javax.swing.JTextField text){
        if(text.getForeground()== Color.GRAY){
            text.setText("");
            text.setForeground(new JTextField().getForeground());
        }
    }
    //para que aparezca el texto Placeholder correspondiente cuando se da click fuera del textfield
    private void placeHolderOut(javax.swing.JTextField text, String msg){
        if(text.getText().equals("")){
            text.setText(msg);
            text.setForeground(Color.GRAY);
        }
    }
    private void soloNum(javax.swing.JTextField text, java.awt.event.KeyEvent evento){
        Object objeto= evento.getKeyChar();
        String key= objeto.toString();
        try{
            Integer.parseInt(key);
        }
        catch(NumberFormatException e){
            if(evento.getKeyCode() != KeyEvent.VK_BACK_SPACE && 
                    evento.getKeyCode() != KeyEvent.VK_LEFT && 
                    evento.getKeyCode() != KeyEvent.VK_RIGHT && 
                    evento.getKeyCode() != KeyEvent.VK_SHIFT){
                String nuevaCad= "";
                char[] cadActual= text.getText().toCharArray();
                for(int i= 0; i < cadActual.length - 1; i++)
                    nuevaCad+= cadActual[i];
                text.setText(nuevaCad);
            }
        }
    }
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        Object item= jComboBox1.getModel().getSelectedItem();
        Object[] items;
        if(item.equals("Windows XP"))items= new Object[]{"Home","Professional","Media Center","64 bit"};
        else if(item.equals("Windows 7")) items= new Object[]{"Starter","Home basic","Home Premium","Professional","Ultimate","Enterpise"};
        else if(item.equals("Windows 8.1"))items= new Object[]{"Core","Pro","Enterprise"};
        else if(item.equals("Windows 10"))items= new Object[]{"Home","Pro","Enterprise","Education"};
        else if(item.equals("Windows 11"))items= new Object[]{"Home","Pro","Enterprise","Education"};
        else if(item.equals("Linux"))items= new Object[]{"Ubuntu","Fedora","Debian","Arch linux"};
        else return;
        ComboBoxModel model= new DefaultComboBoxModel(items);
        jComboBox2.setModel(model);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        placeHolderIn(jTextField4);
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        placeHolderOut(jTextField4, "Versión");
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        placeHolderIn(jTextField5);
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        placeHolderOut(jTextField5, "Nombre");
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        placeHolderIn(jTextField6);
    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        placeHolderOut(jTextField6, "Marca");
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
        placeHolderIn(jTextField7);
    }//GEN-LAST:event_jTextField7FocusGained

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        placeHolderOut(jTextField7, "Modelo");
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        placeHolderIn(jTextField8);
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        placeHolderOut(jTextField8, "No. Serie");
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusGained
        placeHolderIn(jTextField9);
    }//GEN-LAST:event_jTextField9FocusGained

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        placeHolderOut(jTextField9, "Marca");
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusGained
        placeHolderIn(jTextField10);
    }//GEN-LAST:event_jTextField10FocusGained

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        placeHolderOut(jTextField10, "Modelo");
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusGained
        placeHolderIn(jTextField11);
    }//GEN-LAST:event_jTextField11FocusGained

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        placeHolderOut(jTextField11, "Marca");
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusGained
        placeHolderIn(jTextField12);
    }//GEN-LAST:event_jTextField12FocusGained

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        placeHolderOut(jTextField12, "Modelo");
    }//GEN-LAST:event_jTextField12FocusLost

    private void jTextField13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusGained
        placeHolderIn(jTextField13);
    }//GEN-LAST:event_jTextField13FocusGained

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        placeHolderOut(jTextField13, "No. Serie");
    }//GEN-LAST:event_jTextField13FocusLost

    private void jTextField14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusGained
        placeHolderIn(jTextField14);
    }//GEN-LAST:event_jTextField14FocusGained

    private void jTextField14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusLost
        placeHolderOut(jTextField14, "Marca");
    }//GEN-LAST:event_jTextField14FocusLost

    private void jTextField15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField15FocusGained
        placeHolderIn(jTextField15);
    }//GEN-LAST:event_jTextField15FocusGained

    private void jTextField15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField15FocusLost
        placeHolderOut(jTextField15, "Modelo");
    }//GEN-LAST:event_jTextField15FocusLost

    private void jTextField16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField16FocusGained
        placeHolderIn(jTextField16);
    }//GEN-LAST:event_jTextField16FocusGained

    private void jTextField16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField16FocusLost
        placeHolderOut(jTextField16, "No. Serie");
    }//GEN-LAST:event_jTextField16FocusLost

    private void jTextField17FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField17FocusGained
        placeHolderIn(jTextField17);
    }//GEN-LAST:event_jTextField17FocusGained

    private void jTextField17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField17FocusLost
        placeHolderOut(jTextField17, "Marca");
    }//GEN-LAST:event_jTextField17FocusLost

    private void jTextField18FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField18FocusGained
        placeHolderIn(jTextField18);
    }//GEN-LAST:event_jTextField18FocusGained

    private void jTextField18FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField18FocusLost
        placeHolderOut(jTextField18, "Modelo");
    }//GEN-LAST:event_jTextField18FocusLost

    private void jTextField19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField19FocusGained
        placeHolderIn(jTextField19);
    }//GEN-LAST:event_jTextField19FocusGained

    private void jTextField19FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField19FocusLost
        placeHolderOut(jTextField19, "No. Serie");
    }//GEN-LAST:event_jTextField19FocusLost

    private void jTextField20FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField20FocusGained
        placeHolderIn(jTextField20);
    }//GEN-LAST:event_jTextField20FocusGained

    private void jTextField20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField20FocusLost
        placeHolderOut(jTextField20, "Marca");
    }//GEN-LAST:event_jTextField20FocusLost

    private void jTextField21FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField21FocusGained
        placeHolderIn(jTextField21);
    }//GEN-LAST:event_jTextField21FocusGained

    private void jTextField21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField21FocusLost
        placeHolderOut(jTextField21, "Modelo");
    }//GEN-LAST:event_jTextField21FocusLost

    private void jTextField22FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField22FocusGained
        placeHolderIn(jTextField22);
    }//GEN-LAST:event_jTextField22FocusGained

    private void jTextField22FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField22FocusLost
        placeHolderOut(jTextField22, "No. Serie");
    }//GEN-LAST:event_jTextField22FocusLost

    private void jTextField23FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField23FocusGained
        placeHolderIn(jTextField23);
    }//GEN-LAST:event_jTextField23FocusGained

    private void jTextField23FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField23FocusLost
        placeHolderOut(jTextField23, "Marca");
    }//GEN-LAST:event_jTextField23FocusLost

    private void jTextField24FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField24FocusGained
        placeHolderIn(jTextField24);
    }//GEN-LAST:event_jTextField24FocusGained

    private void jTextField24FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField24FocusLost
        placeHolderOut(jTextField24, "Modelo");
    }//GEN-LAST:event_jTextField24FocusLost

    private void jTextField25FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField25FocusGained
        placeHolderIn(jTextField25);
    }//GEN-LAST:event_jTextField25FocusGained

    private void jTextField25FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField25FocusLost
        placeHolderOut(jTextField25, "No. Serie");
    }//GEN-LAST:event_jTextField25FocusLost

    private void jTextField26FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField26FocusGained
        placeHolderIn(jTextField26);
    }//GEN-LAST:event_jTextField26FocusGained

    private void jTextField26FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField26FocusLost
        placeHolderOut(jTextField26, "Marca");
    }//GEN-LAST:event_jTextField26FocusLost

    private void jTextField27FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField27FocusGained
        placeHolderIn(jTextField27);
    }//GEN-LAST:event_jTextField27FocusGained

    private void jTextField27FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField27FocusLost
        placeHolderOut(jTextField27, "Modelo");
    }//GEN-LAST:event_jTextField27FocusLost

    private void jTextField28FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField28FocusGained
        placeHolderIn(jTextField28);
    }//GEN-LAST:event_jTextField28FocusGained

    private void jTextField28FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField28FocusLost
        placeHolderOut(jTextField28, "No. Serie");
    }//GEN-LAST:event_jTextField28FocusLost

    private void jTextField29FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField29FocusGained
        placeHolderIn(jTextField29);
    }//GEN-LAST:event_jTextField29FocusGained

    private void jTextField29FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField29FocusLost
        placeHolderOut(jTextField29, "Marca");
    }//GEN-LAST:event_jTextField29FocusLost

    private void jTextField30FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField30FocusGained
        placeHolderIn(jTextField30);
    }//GEN-LAST:event_jTextField30FocusGained

    private void jTextField30FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField30FocusLost
        placeHolderOut(jTextField30, "Modelo");
    }//GEN-LAST:event_jTextField30FocusLost

    private void jTextField31FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField31FocusGained
        placeHolderIn(jTextField31);
    }//GEN-LAST:event_jTextField31FocusGained

    private void jTextField31FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField31FocusLost
        placeHolderOut(jTextField31, "No. Serie");
    }//GEN-LAST:event_jTextField31FocusLost

    private void jTextField32FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField32FocusGained
        placeHolderIn(jTextField32);
    }//GEN-LAST:event_jTextField32FocusGained

    private void jTextField32FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField32FocusLost
        placeHolderOut(jTextField32, "Marca");
    }//GEN-LAST:event_jTextField32FocusLost

    private void jTextField33FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField33FocusGained
        placeHolderIn(jTextField33);
    }//GEN-LAST:event_jTextField33FocusGained

    private void jTextField33FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField33FocusLost
        placeHolderOut(jTextField33, "Modelo");
    }//GEN-LAST:event_jTextField33FocusLost

    private void jTextField34FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField34FocusGained
        placeHolderIn(jTextField34);
    }//GEN-LAST:event_jTextField34FocusGained

    private void jTextField34FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField34FocusLost
        placeHolderOut(jTextField34, "No. Serie");
    }//GEN-LAST:event_jTextField34FocusLost

    private void jTextField35FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField35FocusGained
        placeHolderIn(jTextField35);
    }//GEN-LAST:event_jTextField35FocusGained

    private void jTextField35FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField35FocusLost
        placeHolderOut(jTextField35, "Marca");
    }//GEN-LAST:event_jTextField35FocusLost

    private void jTextField36FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField36FocusGained
        placeHolderIn(jTextField36);
    }//GEN-LAST:event_jTextField36FocusGained

    private void jTextField36FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField36FocusLost
        placeHolderOut(jTextField36, "Modelo");
    }//GEN-LAST:event_jTextField36FocusLost

    private void jTextField37FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField37FocusGained
        placeHolderIn(jTextField37);
    }//GEN-LAST:event_jTextField37FocusGained

    private void jTextField37FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField37FocusLost
        placeHolderOut(jTextField37, "No. Serie");
    }//GEN-LAST:event_jTextField37FocusLost

    private void jTextField38FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField38FocusGained
        placeHolderIn(jTextField38);
    }//GEN-LAST:event_jTextField38FocusGained

    private void jTextField38FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField38FocusLost
        placeHolderOut(jTextField38, "Marca");
    }//GEN-LAST:event_jTextField38FocusLost

    private void jTextField39FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField39FocusGained
        placeHolderIn(jTextField39);
    }//GEN-LAST:event_jTextField39FocusGained

    private void jTextField39FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField39FocusLost
        placeHolderOut(jTextField39, "Modelo");
    }//GEN-LAST:event_jTextField39FocusLost

    private void jTextField40FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField40FocusGained
        placeHolderIn(jTextField40);
    }//GEN-LAST:event_jTextField40FocusGained

    private void jTextField40FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField40FocusLost
        placeHolderOut(jTextField40, "No. Serie");
    }//GEN-LAST:event_jTextField40FocusLost

    private void jTextField41FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField41FocusGained
        placeHolderIn(jTextField41);
    }//GEN-LAST:event_jTextField41FocusGained

    private void jTextField41FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField41FocusLost
        placeHolderOut(jTextField41, "Marca");
    }//GEN-LAST:event_jTextField41FocusLost

    private void jTextField42FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField42FocusGained
        placeHolderIn(jTextField42);
    }//GEN-LAST:event_jTextField42FocusGained

    private void jTextField42FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField42FocusLost
        placeHolderOut(jTextField42, "Modelo");
    }//GEN-LAST:event_jTextField42FocusLost

    private void jTextField43FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField43FocusGained
        placeHolderIn(jTextField43);
    }//GEN-LAST:event_jTextField43FocusGained

    private void jTextField43FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField43FocusLost
        placeHolderOut(jTextField43, "No. Serie");
    }//GEN-LAST:event_jTextField43FocusLost

    private void jTextField44FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField44FocusGained
        placeHolderIn(jTextField44);
    }//GEN-LAST:event_jTextField44FocusGained

    private void jTextField44FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField44FocusLost
        placeHolderOut(jTextField44, "Marca");
    }//GEN-LAST:event_jTextField44FocusLost

    private void jTextField45FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField45FocusGained
        placeHolderIn(jTextField45);
    }//GEN-LAST:event_jTextField45FocusGained

    private void jTextField45FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField45FocusLost
        placeHolderOut(jTextField45, "Modelo");
    }//GEN-LAST:event_jTextField45FocusLost

    private void jTextField46FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField46FocusGained
        placeHolderIn(jTextField46);
    }//GEN-LAST:event_jTextField46FocusGained

    private void jTextField46FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField46FocusLost
        placeHolderOut(jTextField46, "No. Serie");
    }//GEN-LAST:event_jTextField46FocusLost

    private void jTextField47FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField47FocusGained
        placeHolderIn(jTextField47);
    }//GEN-LAST:event_jTextField47FocusGained

    private void jTextField47FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField47FocusLost
        placeHolderOut(jTextField47, "Marca");
    }//GEN-LAST:event_jTextField47FocusLost

    private void jTextField48FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField48FocusGained
        placeHolderIn(jTextField48);
    }//GEN-LAST:event_jTextField48FocusGained

    private void jTextField48FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField48FocusLost
        placeHolderOut(jTextField48, "Modelo");
    }//GEN-LAST:event_jTextField48FocusLost

    private void jTextField49FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField49FocusGained
        placeHolderIn(jTextField49);
    }//GEN-LAST:event_jTextField49FocusGained

    private void jTextField49FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField49FocusLost
        placeHolderOut(jTextField49, "No. Serie");
    }//GEN-LAST:event_jTextField49FocusLost

    private void jTextField50FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField50FocusGained
        placeHolderIn(jTextField50);
    }//GEN-LAST:event_jTextField50FocusGained

    private void jTextField50FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField50FocusLost
        placeHolderOut(jTextField50, "No. Inventario");
    }//GEN-LAST:event_jTextField50FocusLost

    private void jTextField50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField50KeyReleased
        soloNum(jTextField50, evt);
    }//GEN-LAST:event_jTextField50KeyReleased

    private void jTextField51FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField51FocusGained
        placeHolderIn(jTextField51);
    }//GEN-LAST:event_jTextField51FocusGained

    private void jTextField51FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField51FocusLost
        placeHolderOut(jTextField51, "No. Inventario");
    }//GEN-LAST:event_jTextField51FocusLost

    private void jTextField51KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField51KeyReleased
        soloNum(jTextField51, evt);
    }//GEN-LAST:event_jTextField51KeyReleased

    private void jTextField52FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField52FocusGained
        placeHolderIn(jTextField52);
    }//GEN-LAST:event_jTextField52FocusGained

    private void jTextField52FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField52FocusLost
        placeHolderOut(jTextField52, "No. Inventario");
    }//GEN-LAST:event_jTextField52FocusLost

    private void jTextField52KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField52KeyReleased
        soloNum(jTextField52, evt);
    }//GEN-LAST:event_jTextField52KeyReleased

    private void jTextField53FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField53FocusGained
        placeHolderIn(jTextField53);
    }//GEN-LAST:event_jTextField53FocusGained

    private void jTextField53FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField53FocusLost
        placeHolderOut(jTextField53, "No. Inventario");
    }//GEN-LAST:event_jTextField53FocusLost

    private void jTextField53KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField53KeyReleased
        soloNum(jTextField53, evt);
    }//GEN-LAST:event_jTextField53KeyReleased

    private void jTextField54FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField54FocusGained
        placeHolderIn(jTextField54);
    }//GEN-LAST:event_jTextField54FocusGained

    private void jTextField54FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField54FocusLost
        placeHolderOut(jTextField54, "No. Inventario");
    }//GEN-LAST:event_jTextField54FocusLost

    private void jTextField54KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField54KeyReleased
        soloNum(jTextField54, evt);
    }//GEN-LAST:event_jTextField54KeyReleased

    private void jTextField55FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField55FocusGained
        placeHolderIn(jTextField55);
    }//GEN-LAST:event_jTextField55FocusGained

    private void jTextField55FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField55FocusLost
        placeHolderOut(jTextField55, "No. Inventario");
    }//GEN-LAST:event_jTextField55FocusLost

    private void jTextField55KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField55KeyReleased
        soloNum(jTextField55, evt);
    }//GEN-LAST:event_jTextField55KeyReleased

    private List<Component> getHermanos(JLabel objetivo){
        List<Component> hermanos= new LinkedList<>();
        Container padre= objetivo.getParent();
        for(Component hijo : padre.getComponents()){
            if(hijo instanceof JLabel)
                continue;
            hermanos.add(hijo);
        }
        return hermanos;
    }
    
    private void getLabels(Container inicio, List<JLabel> labels){
        for(Component elem : inicio.getComponents()){
            if(elem instanceof JLabel label && !label.getText().equals("."))
                labels.add(label);
            else if(elem instanceof JPanel contenedor) getLabels(contenedor, labels);
        }
    }
    
    //acción del botón "Guardar"
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Map<String,List<Object>> equipoNew= new HashMap<>();
        Boolean vacios= false;
        Boolean datosIncompletos= false;
        List<JLabel> labels= new LinkedList<>();  //conteandrá las claves referentes a los atributos del equipo informático
        getLabels(jPanel1, labels);
        // <editor-fold defaultstate="collapsed" desc="Recopilar información y validación"> 
        for(JLabel etiqueta : labels){
            List<Object> hermanos= new LinkedList<>(); //contendrá los valores que se guardarán por clave
            String clave= etiqueta.getText().split(":")[0];  //para quitar los 2 puntos de la clave
            clave= clave.equals("Monitor")? "Monitor 1" : clave; //cambio "Monitor" por "Monitor 1" si fuera el caso
            clave= clave.equals("Disco Duro")? "Disco Duro 1" : clave; //cambio "Disco Duro" por "Disco Duro 1" si fuera el caso
            Integer cantValidadosOK= 0;  //solo se guardarán las claves que tengan todos los valores validados
            for(Component control : getHermanos(etiqueta)){
                Object valor= "";
                if(control instanceof JTextField textField){
                    valor= textField.getText();
                    if(!valor.equals("") && !valor.equals("Nombre") && !valor.equals("Cargo") && 
                            !valor.equals("Versión") && !valor.equals("Marca") && !valor.equals("Modelo") && 
                            !valor.equals("No. Serie") && !valor.equals("No. Inventario")){
                        textField.setBorder(new JTextField().getBorder());
                        cantValidadosOK++;
                    }
                    else if(!clave.equals("Lector CD/DVD") && !clave.equals("Lector 3 1/2") && 
                            !clave.equals("UPS") && !clave.equals("Impresora") && !clave.equals("Scanner") && 
                            !clave.equals("Fotocopiadora")){
                        textField.setBorder(new LineBorder(Color.RED, 2));
                        //esta asignacion es superimportante
                        //si hay algun campo vacio no permite el paso de la informacion al controlador
                        vacios= true;
                    }
                }
                else if(control instanceof JComboBox comboBox){
                    if(comboBox.isEditable()) valor= comboBox.getEditor().getItem();
                    else valor= comboBox.getSelectedItem();
                    if(!valor.equals("")){
                        comboBox.setBorder(new JComboBox<>().getBorder());
                        cantValidadosOK++;
                    }
                    else if(!clave.equals("Lector CD/DVD") && !clave.equals("Lector 3 1/2") &&
                            !clave.equals("UPS") && !clave.equals("Impresora") && !clave.equals("Scanner") &&
                            !clave.equals("Fotocopiadora")){
                        comboBox.setBorder(new LineBorder(Color.RED, 2));
                        //lo mismo que arriba
                        vacios= true;
                    }
                }
                else if(control instanceof JSpinner spinner){
                    valor= spinner.getValue();
                    cantValidadosOK++;
                }
                hermanos.add(valor);
            }
            /*agrega cada componente y propiedad que tenga sus datos completos 
            al equipo nuevo que se va a registrar*/
            if(cantValidadosOK.equals(hermanos.size())) equipoNew.put(clave, hermanos);
            /*si hay algun dispositivo o componente con datos incompletos mostrará una advertencia,
            esto es para los dispositivos o periféricos prescindibles*/
            else if(cantValidadosOK != 0) datosIncompletos= true;
            //agrega el id en null a cada dispositivo o periférico agregado
            if(equipoNew.get(clave) != null && !clave.equals("Nombre del equipo (RED)") 
                    && !clave.equals("Tipo") && !clave.equals("IP") && !clave.equals("Departamento") 
                    && !clave.equals("No. Sello") && !clave.equals("No. Llavero") && !clave.equals("Estado"))
                equipoNew.get(clave).add(null);
        }
        //</editor-fold>
        //como dije antes si esto se cumple no se permite el paso de la informacion al controlador
        if(vacios){
            JOptionPane.showMessageDialog(this, "Hay campos vacios que son obligatorios\n " + 
                    "Mire los campos con bordes en rojo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(datosIncompletos){
            JOptionPane.showMessageDialog(this, "Hay dispositivos prescindibles con datos incompletos\n " + 
                    "No se guardarán en la BD si no se completan", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //a partir de aqui se hace el envio de los datos hacia el controlador
        gestionEquipo controlador= new gestionEquipo();
        String estado= controlador.registrarComputadora(equipoNew, "agregar");
        JOptionPane.showMessageDialog(this, estado, "Información", JOptionPane.INFORMATION_MESSAGE);
        if(estado.equals("El equipo se registró correctamente en la BD")){
            String nombreAdmin= ((Vista.Inicio)this.getOwner()).getNombreAdmin();
            Controlador.gestionEventos.agregarEvento("Responsable: " + nombreAdmin + "\n" + 
                    "Lugar: Sistema\n" + "El administrador agregó una nueva computadora " + 
                    "con el nombre " + equipoNew.get("Nombre del equipo (RED)").getFirst());
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        placeHolderIn(jTextField1);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        placeHolderOut(jTextField1, "Nombre");
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField56FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField56FocusGained
        placeHolderIn(jTextField56);
    }//GEN-LAST:event_jTextField56FocusGained

    private void jTextField56FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField56FocusLost
        placeHolderOut(jTextField56, "Cargo");
    }//GEN-LAST:event_jTextField56FocusLost

    /*cambia el icono del tipo de computadora cuando el valor del comboBox cambia
    entre PC, Laptop o Servidor*/
    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged
        String tema= OpcionesConfig.cargarTema();
        List<Object> tipos= new ArrayList<>(List.of("PC", "Servidor"));
        if(tipos.contains(jComboBox6.getSelectedItem())){
            if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire"))
                jLabel27.setIcon(new ImageIcon(getClass().getResource("/Iconos/PC_b.png")));
            else jLabel27.setIcon(new ImageIcon(getClass().getResource("/Iconos/PC.png")));
        }
        else {
            if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire"))
                jLabel27.setIcon(new ImageIcon(getClass().getResource("/Iconos/laptop_b.png")));
            else jLabel27.setIcon(new ImageIcon(getClass().getResource("/Iconos/laptop.png")));
        }
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    //listener que mantiene el valor del primer spinner de la "IP" entre 0 y 255
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        int valor= Integer.parseInt(jSpinner1.getValue().toString());
        if(valor < 0) jSpinner1.setValue(0);
        else if(valor > 255) jSpinner1.setValue(255);
    }//GEN-LAST:event_jSpinner1StateChanged

    //listener que mantiene el valor del segundo spinner de la "IP" entre 0 y 255
    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        int valor= Integer.parseInt(jSpinner3.getValue().toString());
        if(valor < 0) jSpinner3.setValue(0);
        else if(valor > 255) jSpinner3.setValue(255);
    }//GEN-LAST:event_jSpinner3StateChanged

    //listener que mantiene el valor del tercer spinner de la "IP" entre 0 y 255
    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        int valor= Integer.parseInt(jSpinner4.getValue().toString());
        if(valor < 0) jSpinner4.setValue(0);
        else if(valor > 255) jSpinner4.setValue(255);
    }//GEN-LAST:event_jSpinner4StateChanged

    //listener que mantiene el valor del cuarto spinner de la "IP" entre 0 y 255
    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        int valor= Integer.parseInt(jSpinner2.getValue().toString());
        if(valor < 0) jSpinner2.setValue(0);
        else if(valor > 255) jSpinner2.setValue(255);
    }//GEN-LAST:event_jSpinner2StateChanged

    //listener que mantiene el valor del spinner del "No. Sello" por encima de 0
    private void jSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner5StateChanged
        int valor= Integer.parseInt(jSpinner5.getValue().toString());
        if(valor < 1) jSpinner5.setValue(1);
    }//GEN-LAST:event_jSpinner5StateChanged

    //listener que mantiene el valor del spinner del "No. Llavero" por encima de 0
    private void jSpinner6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner6StateChanged
        int valor= Integer.parseInt(jSpinner6.getValue().toString());
        if(valor < 1) jSpinner6.setValue(1);
    }//GEN-LAST:event_jSpinner6StateChanged

    private void cargarIconosBParaTemasN(){
        String tema= OpcionesConfig.cargarTema();
        if(tema.contains("Dar") || tema.contains("HiFi") || tema.contains("Noire")){
            jLabel27.setIcon(new ImageIcon(getClass().getResource("/Iconos/PC_b.png")));
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/Iconos/lan_b.png")));
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Iconos/usuario_b.png")));
            jLabel6.setIcon(new ImageIcon(getClass().getResource("/Iconos/departamento_b.png")));
            jLabel10.setIcon(new ImageIcon(getClass().getResource("/Iconos/llavero_b.png")));
            jLabel11.setIcon(new ImageIcon(getClass().getResource("/Iconos/CPU_b.png")));
            jLabel18.setIcon(new ImageIcon(getClass().getResource("/Iconos/mouse_b.png")));
            jLabel23.setIcon(new ImageIcon(getClass().getResource("/Iconos/UPS_b.png")));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
