/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ClienteLAN;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author PC
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        cliente= new ClienteLAN();
        jTextField1.setText(cargarIpServidor());
        hilo= new Thread();
        Connect= false;
        jToggleButton1.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agente Local (Cliente) del LMC v1.0 - Petroempleo");
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/logo.png")).getImage());
        setPreferredSize(new java.awt.Dimension(400, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel8.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/flechaDown.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3);

        jPanel4.add(jPanel6);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/play32x32.png"))); // NOI18N
        jToggleButton1.setText("Conectar");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.setIconTextGap(10);
        jToggleButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/playNublado32x32.png"))); // NOI18N
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/playSoleado32x32.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);

        jPanel4.add(jPanel2);

        jPanel8.add(jPanel4, "card3");

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel1.setText("IP del Servidor:");
        jPanel1.add(jLabel1);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0.0.0.0");
        jTextField1.setPreferredSize(new java.awt.Dimension(120, 30));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);

        jPanel5.add(jPanel1);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel2.setText("Generar Truststore");
        jPanel3.add(jLabel2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/generar32x32.png"))); // NOI18N
        jButton1.setToolTipText("Generar archivo \"cliente.truststore\" para establecer la conexión segura");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel5.add(jPanel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/flechaUp.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel4);

        jPanel5.add(jPanel7);

        jPanel8.add(jPanel5, "card2");

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //conectarse o desconectarse del servidor
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(cliente.estaConectado() || hilo.isAlive()){
            cliente.disconect();
            Connect= false;
            synchronized (block) {
                block.notify();
            }
            jToggleButton1.setText("Conectar");
            jToggleButton1.setIcon(new ImageIcon(getClass().getResource("/Iconos/play32x32.png")));
            jToggleButton1.setPressedIcon(new ImageIcon(getClass().getResource("/Iconos/playNublado32x32.png")));
            jToggleButton1.setRolloverIcon(new ImageIcon(getClass().getResource("/Iconos/playSoleado32x32.png")));
        } 
        else {
            Connect= true;
            hilo= new Thread(()->{
                try{
                    while(Connect){
                        String ipServidor= jTextField1.getText();
                        if(!ipServidor.equals(cargarIpServidor())){
                            try(ObjectOutputStream out= new ObjectOutputStream(new FileOutputStream("config.cfg"))){
                                out.writeObject(ipServidor);
                            }catch(IOException e){
                                JOptionPane.showMessageDialog(this, e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        cliente.configurarTrustStore("cliente.truststore", "Seraphim#1");
                        cliente.connect(ipServidor, 8000);
                        if(cliente.estaConectado()){
                            try{
                                synchronized (block) {
                                    block.wait();
                                }
                            }catch(InterruptedException e){
                                break;
                            }
                        }
                        try{
                            Thread.sleep(10000);
                        }catch(InterruptedException e){
                            break;
                        }
                    }
                }catch(RuntimeException e){
                    String msg= e.getMessage();
                    if(msg.contains("El sistema no puede encontrar el archivo especificado"))
                        msg+= "\n\nVuelva a generar un nuevo truststore, asegurese de tener el certificado";
                    JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
                    jToggleButton1.setText("Conectar");
                    jToggleButton1.setIcon(new ImageIcon(getClass().getResource("/Iconos/play32x32.png")));
                    jToggleButton1.setPressedIcon(new ImageIcon(getClass().getResource("/Iconos/playNublado32x32.png")));
                    jToggleButton1.setRolloverIcon(new ImageIcon(getClass().getResource("/Iconos/playSoleado32x32.png")));
                    jToggleButton1.setSelected(false);
                }
            });
            hilo.start();
            jToggleButton1.setText("Desconectar");
            jToggleButton1.setIcon(new ImageIcon(getClass().getResource("/Iconos/stop32x32.png")));
            jToggleButton1.setPressedIcon(new ImageIcon(getClass().getResource("/Iconos/stopNublado32x32.png")));
            jToggleButton1.setRolloverIcon(new ImageIcon(getClass().getResource("/Iconos/stopSoleado32x32.png")));
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    //acción cuando se escribe en la dirección IP
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        formatJTextFieldForIP(jTextField1, evt);
    }//GEN-LAST:event_jTextField1KeyPressed

    //acción cuando se borra algún carácter en la dirección IP
    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        formatJTextFieldForIP(jTextField1, evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    //antes de cerrar la ventana termina la conexión
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(cliente.estaConectado() || hilo.isAlive()){
            cliente.disconect();
            Connect= false;
        } 
    }//GEN-LAST:event_formWindowClosing

    //generar un archivo truststore
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileUI= new JFileChooser();
        fileUI.setDialogTitle("Buscar certificado público");
        fileUI.setApproveButtonText("Cargar");
        int resultado= fileUI.showOpenDialog(this);
        if(resultado == JFileChooser.APPROVE_OPTION){
            File file= fileUI.getSelectedFile();
            String fileName= file.getName();
            String filePath= file.getAbsolutePath();
            if(file.exists()){
                if(!fileName.toLowerCase().endsWith(".crt")){
                    JOptionPane.showMessageDialog(this, """
                                                El archivo escogido no es el correcto
                                                Debe ser uno con extensión .crt""",
                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "El archivo no existe",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try{
                Loading loading= new Loading(this, Dialog.ModalityType.APPLICATION_MODAL);
                String[] estado= new String[1];
            
                loading.execMetodo(()-> {
                    estado[0]= generarTrustStore(filePath);
                });
            
                if(estado[0].equals("éxito")){
                    mostrarMSG(this, "El archivo cliente.truststore se generó correctamente");
                }
                else 
                    JOptionPane.showMessageDialog(this, "El archivo cliente.truststore" + 
                            " no se generó", "Error", 
                            JOptionPane.ERROR_MESSAGE);
            }catch(RuntimeException e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //cuando se da click en la flecha hacia abajo despliega las opciones
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        java.awt.CardLayout cardManager= (java.awt.CardLayout)jPanel8.getLayout();
        cardManager.show(jPanel8, "card2");
    }//GEN-LAST:event_jLabel3MouseClicked

    //cuando se da click en la flecha hacia arriba esconde las opciones
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        java.awt.CardLayout cardManager= (java.awt.CardLayout)jPanel8.getLayout();
        cardManager.show(jPanel8, "card3");
    }//GEN-LAST:event_jLabel4MouseClicked

    private String cargarIpServidor(){
        String ip;
        try(ObjectInputStream in= new ObjectInputStream(new FileInputStream("config.cfg"))){
            ip= (String)in.readObject();
        }catch(IOException | ClassNotFoundException e){
            ip= "192.168.0.5";
            try(ObjectOutputStream out= new ObjectOutputStream(new FileOutputStream("config.cfg"))){
                out.writeObject(ip);
            }catch(IOException er){
                JOptionPane.showMessageDialog(this, er.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        return ip;
    }
    
    private String generarTrustStore(String filePath){
        List<String> command= new ArrayList<>();
        command.add("keytool");
        command.add("-importcert");
        command.add("-alias");
        command.add("certificadoLMC");
        command.add("-keystore");
        command.add("cliente.truststore");
        command.add("-storetype");
        command.add("pkcs12");
        command.add("-storepass");
        command.add("Seraphim#1");
        command.add("-file");
        command.add(filePath);
        command.add("-noprompt");
        ProcessBuilder build= new ProcessBuilder(command);
        build.redirectErrorStream(true);
        try{
            Process process= build.start();
            int exitCode= process.waitFor();
            if(exitCode == 0)
                return "éxito";
            else return "fallo";
        }catch(IOException | InterruptedException e){
            throw new RuntimeException(e.getMessage(), e);
        }
    }
    
    /*se evita que se procese el evento de manera normal, o sea, se evita
    que se introduzcan carácteres en el jTextField como se haría normalmente
    y solo se hace de la manera que se define en este método,
    este método se debe usar en los eventos KeyPressed y KeyTyped para que
    funcione bien, no en el evento KeyReleased donde da un comportamiento raro*/
    private void formatJTextFieldForIP(javax.swing.JTextField textoField, java.awt.event.KeyEvent evt){
        //<editor-fold defaultstate="collapsed" desc="código">
        
        /*aqui se procesa el evento cuando se presiona el botón "delete"
        o "backspace" del teclado para borrar carácteres del jtexfield*/
        if(evt.getID() == java.awt.event.KeyEvent.KEY_PRESSED){
            
            //se obtiene el código de tecla presionada
            int code= evt.getKeyCode();
            
            /*si se selecciona un texto y se presiona delete o backspace
            se evita el borrado y se sale de la función*/
            if(code == 8 || code == 127){
                String cadSeleccionada= textoField.getSelectedText();
                if(cadSeleccionada!= null){
                    evt.consume();
                    return;
                }
            }
            
            /*/pos/ permite saber en que lugar del texto
            se va a borrar el carácter*/
            int pos= textoField.getCaretPosition();
            
            //se obtiene el texto del jtextfield
            String ip= textoField.getText();
        
            /*Lista que va a aceptar todas las letras de /ip/
            esta lista sirve para quitar el carácter señalado por /pos/*/
            List<Character> charList= new ArrayList<>();
            
            //Se asigna a /charList/ los carácteres de /ip/
            for(char caracter : ip.toCharArray())
                charList.add(caracter);
            
            /*si se presiona backspace se elimina el carácter señalado por
            /pos/ en /charList/*/
            if(code == java.awt.event.KeyEvent.VK_BACK_SPACE){
                //si esta /pos/ al principio de /ip/ se sale y no continua
                if(pos == 0) return;
                //elimina el carácter señalado
                charList.remove(--pos);
            }
            /*si se presiona delete se elimina el carácter señalado por
            /pos/ en /charList/*/
            else if(code == java.awt.event.KeyEvent.VK_DELETE){
                //si esta /pos/ al final de /ip/ se sale y no continua
                if(pos == ip.length()) return;
                //elimina el carácter señalado
                charList.remove(pos);
            }
            
            /*se asigna a/ip/ el /charList/ modificado*/
            ip= "";
            for(Character caracter : charList)
                ip+= caracter;
                
            /*si se borra un punto de /ip/ o un posible único número entre
            2 puntos se evita que sev procese el evento*/
            String[] ipArray= ip.split("\\.");
            for(String fragmento : ipArray){
                if(fragmento.equals("") || ipArray.length < 4)
                    evt.consume();
            }
            
            return;
        }
        
        //a partir de aqui se procesa el evento cuando se introducen carácteres
        
        /*se evita la introducción de carácteres como lo haría
        el listener por defecto*/
        evt.consume();
        
        char key= evt.getKeyChar(); //se obtiene el carácter introducido
        try{
            /*se trata de convertir el carácter a número, si no es un número
            se lanza la excepción y se sale de la función, asi se evita que
            se introduzcan otros carácteres que no sean números*/
            Integer.valueOf(String.valueOf(key));
        }catch(NumberFormatException e){
            return;
        }
        
        /*si se selecciona un texto y se escribe y este contiene algún punto
        se sale de la función, esto es para evitar quitar los puntos*/
        String cadSeleccionada= textoField.getSelectedText();
        if(cadSeleccionada!= null && cadSeleccionada.contains("."))
            return;
        
        //se obtiene el texto del jtextfield
        String ip= textoField.getText();
        
        /*Lista que va a aceptar todas las letras de /ip/
        esta lista sirve para agregar el carácter introducido /key/*/
        List<Character> charList= new ArrayList<>();
        
        /*esta lista contenfrá los índices de los puntos*/
        List<Integer> puntosIndex= new ArrayList<>();
        
        /*Se asigna a /charList/ los carácteres de /ip/ y a /puntosIndex/
        los índices de los puntos*/
        int index= 0;
        for(char caracter : ip.toCharArray()){
            charList.add(caracter);
            if(caracter == '.')
                puntosIndex.add(index);
            index++;
        }
        
        /*/pos/ permite saber en que lugar del texto
        se va a introducir el carácter*/
        int pos= textoField.getCaretPosition();
        
        String num= ""; //contendrá un número de los 4 que hay en /ip/
        int lugarDigito= 0; //permite saber qué dígito se va a cambiar del número
        
        /*De los 4 números que hay en /ip/ se obtendrá el número donde apunte
        /pos/ y también se obtendrá la posición del dígito que se va a cambiar*/
        if(pos <= puntosIndex.get(0)){
            num= ip.split("\\.")[0];
            lugarDigito= pos;
        }
        else if(pos <= puntosIndex.get(1)){
            num= ip.split("\\.")[1];
            lugarDigito= pos - puntosIndex.get(0) - 1;
        }
        else if(pos <= puntosIndex.get(2)){
            num= ip.split("\\.")[2];
            lugarDigito= pos - puntosIndex.get(1) - 1;
        }
        else if(pos <= ip.length()){
            num= ip.split("\\.")[3];
            lugarDigito= pos - puntosIndex.get(2) - 1;
        }
        
        //si el número tiene 3 dígitos:
        if(num.length() == 3){
            /*si /pos/ apunta al final de /ip/ sale de la función,
            como el número tiene 3 dígitos no se puede introducir más*/
            if(pos == ip.length())
                return;
            /*si /pos/ apunta a un punto ('.') se incrementa en 1 /pos/,
            esto significa que se va a saltar ese carácter*/
            else if(charList.get(pos).equals('.'))
                pos++;
            //si se está en cualquier posición distinta a un punto ('.'):
            else{
                /*se obtiene un array del número para modificar el dígito
                en la posición señalada por /lugarDigito/*/
                char[] numArray= num.toCharArray();
                //se modifica el dígito señalado
                numArray[lugarDigito]= key;
                /*se convierte el número modificado de tipo cadena
                por un número real*/
                int real= Integer.parseInt(String.valueOf(numArray));
                /*si el número real es mayor que 255 se sale de la función,
                esto significa que solo se aceptaran en el ip
                números de 0 a 255*/
                if(real > 255) return;
            }
            /*se modifica /charList/ intercambiando el dígito
            señalado por /pos/ por el carácter o número introducido*/
            charList.set(pos, key);
        }
        //si el número tiene 1 o 2 dígitos:
        else{
            /*si /pos/ apunta al final de /ip/ o a un punto ('.')
            se obtiene el número real(número señalado por /pos/ mas el número
            introducido) y si es menor o igual que 255 se adiciona a /charList/
            (no se intercambia el dígito señalado), sino se sale de la función*/
            if(pos == ip.length() || charList.get(pos).equals('.')){
                int real= Integer.parseInt(String.valueOf(num + key));
                if(real > 255) return;
                charList.add(pos, key);
            }
            /*si se está en cualquier otra posición se modifica /charList/
            intercambiando el dígito señalado por /pos/ por el carácter o
            número introducido*/
            else charList.set(pos, key);
        }
        
        /*se asigna a/ip/ el /charList/ modificado*/
        ip= "";
        for(Character caracter : charList)
            ip+= caracter;
        
        //se quitan los ceros que hay delante de los números como 06, 008
        String[] ipArray= ip.split("\\.");
        ip= "";
        for(String fragmento : ipArray){
            int real= Integer.parseInt(fragmento);
            ip+= real + ".";
        }
        //se quita el último carácter que es '.'
        ip= ip.substring(0, ip.length() - 1);
        
        //se asigna al jtextfield el nuevo ip
        textoField.setText(ip);
        
        //se posiciona el caret un lugar después de donde /pos/ señala
        if(pos < ip.length()) pos++;
        textoField.setCaretPosition(pos);
        
        //</editor-fold>
    }
    
    private void mostrarMSG(java.awt.Component padre, String mensaje){
        //<editor-fold defaultstate="collapsed" desc="muestra cuadro de mensaje como un tooltip que desaparece a los 3 segundos">
        JDialog msg= new JDialog();
        msg.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        msg.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        String[] msgSplit= mensaje.split("\n");
        for(int i= 0, max= 0, y= 0; i < msgSplit.length; i++){
            JLabel texto= new JLabel();
            texto.setForeground(Color.BLACK);
            texto.setText(msgSplit[i]);
            max= texto.getText().length() > max? texto.getText().length() : max;
            msg.setPreferredSize(new Dimension(max * 7, y += 30));
            msg.getContentPane().add(texto);
        }
        msg.setUndecorated(true);
        msg.getContentPane().setBackground(Color.GREEN);
        msg.getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER));
        msg.pack();
        msg.setLocationRelativeTo(padre);
        new Thread(()->{
            try{
                Thread.sleep(3000);
                //esto es para mostrar un efecto fade off antes de desaparecer msg.
                float[] fadeValues= new float[]{0.8f, 0.6f, 0.4f, 0.2f};
                for(int i= 0; i < 4; i++){
                    msg.setOpacity(fadeValues[i]);
                    Thread.sleep(100);
                }
                msg.setOpacity(0);
            }
            catch(InterruptedException e){e.printStackTrace();}
            msg.dispose();
        }).start();
        msg.setVisible(true);
        //</editor-fold>
    }
    
    private final ClienteLAN cliente;
    private volatile boolean Connect;
    private Thread hilo;
    private final Object block= new Object();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
